PROFESSIONAL_SKILLS = [
    'Accessibility',
    'Android development',
    'Assembly',
    'Backend web development',
    'Bioinformatics',
    'Bootstrap',
    'Chemistry',
    'C programming',
    'C++',
    'Computer Networking',
    'Continuous integration',
    'Copywriting',
    'CSS',
    'Cybersecurity',
    'Data analysis',
    'Data science',
    'Data visualization',
    'Databases',
    'Debian packaging',
    'Distributed computing',
    'Django',
    'Docker',
    'Figma',
    'Flask',
    'Flutter',
    'Front-end web development',
    'Functional programming',
    'Git source control',
    'GitHub workflow',
    'GitLab workflow',
    'Graphic design',
    'Golang',
    'Gtk',
    'Hardware design',
    'HTML',
    'Hugo',
    'Illustration',
    'Internationalization',
    'JavaScript',
    'Jekyll',
    'Julia',
    'Java',
    'Jupyter notebooks',
    'jquery',
    'JSON',
    'Kubernetes',
    'Linux',
    'Linux command line',
    'Linux shell scripting',
    'Localization',
    'Markdown',
    'Machine Learning',
    'MySQL',
    'NodeJS',
    'Objective C',
    'OCaml',
    'Operating Systems',
    'perl',
    'PHP',
    'Privacy technology',
    'Product management',
    'Postgresql',
    'Python',
    'R',
    'ReactJS',
    'React Native',
    'Regular expressions',
    'Research',
    'Ruby',
    'Rust',
    'Security',
    'Shell scripting',
    'Social media management',
    'Software testing',
    'systemd',
    'SQL',
    'Test driven development',
    'Technical writing',
    'Typescript',
    'UIUX Design',
    'Video editing',
    'VueJS',
    'Web development',
    'Wireframing',
    'XML',
    'YAML',
]