from . import views
from django.views.generic import TemplateView

from django.conf.urls import include, url

# These views all take both a community_slug and a project_slug.
project_cfp_patterns = [
    url(r'^mentor/preview/(?P<username>[^/]+)/$', views.MentorApprovalPreview.as_view(), name='mentorapproval-preview'),
    url(r'^mentor/(?P<action>[^/]+)/(?:(?P<username>[^/]+)/)?$', views.MentorApprovalAction.as_view(), name='mentorapproval-action'),
    url(r'^skills/$', views.ProjectSkillsEditPage.as_view(), name='project-skills-edit'),
    url(r'^channels/$', views.CommunicationChannelsEditPage.as_view(), name='communication-channels-edit'),
    url(r'^$', views.project_read_only_view, name='project-read-only'),
]

# These views all take a community_slug.
community_cfp_patterns = [
    url(r'^edit/$', views.CommunityUpdate.as_view(), name='community-update'),
    url(r'^notify/$', views.CommunityNotificationUpdate.as_view(), name='notify-me'),
    url(r'^coordinator/preview/(?P<username>[^/]+)/$', views.CoordinatorApprovalPreview.as_view(), name='coordinatorapproval-preview'),
    url(r'^coordinator/(?P<action>[^/]+)/(?:(?P<username>[^/]+)/)?$', views.CoordinatorApprovalAction.as_view(), name='coordinatorapproval-action'),
    url(r'^project/(?P<project_slug>[^/]+)/', include(project_cfp_patterns)),
    url(r'^(?P<action>[^/]+)-project/(?:(?P<project_slug>[^/]+)/)?$', views.ProjectAction.as_view(), name='project-action'),
    url(r'^(?P<action>[^/]+)/$', views.ParticipationAction.as_view(), name='participation-action'),
    url(r'^$', views.community_read_only_view, name='community-read-only'),
]

urlpatterns = [
    url(r'^communities/cfp/add/$', views.CommunityCreate.as_view(), name='community-add'),
    url(r'^communities/cfp/(?P<community_slug>[^/]+)/', include(community_cfp_patterns)),
    url(r'^(?P<round_slug>[^/]+)/communities/(?P<community_slug>[^/]+)/(?P<project_slug>[^/]+)/intern-agreement/$', views.InternAgreementSign.as_view(), name='intern-agreement'),
    url(r'^(?P<round_slug>[^/]+)/communities/(?P<community_slug>[^/]+)/(?P<project_slug>[^/]+)/alum-standing/(?P<applicant_username>[^/]+)/(?P<standing>[^/]+)$', views.AlumStanding.as_view(), name='alum-standing'),
    url(r'^(?P<round_slug>[^/]+)/communities/(?P<community_slug>[^/]+)/(?P<project_slug>[^/]+)/final-application/(?P<applicant_username>[^/]+)/select/?$', views.InternSelectionUpdate.as_view(), name='select-intern'),
    url(r'^(?P<round_slug>[^/]+)/communities/(?P<community_slug>[^/]+)/(?P<project_slug>[^/]+)/final-application/(?P<applicant_username>[^/]+)/remove/?$', views.InternRemoval.as_view(), name='remove-intern'),
    url(r'^(?P<round_slug>[^/]+)/communities/(?P<community_slug>[^/]+)/(?P<project_slug>[^/]+)/final-application/(?P<applicant_username>[^/]+)/resign/?$', views.MentorResignation.as_view(), name='resign-as-mentor'),
    url(r'^(?P<round_slug>[^/]+)/communities/(?P<community_slug>[^/]+)/(?P<project_slug>[^/]+)/mentor-contract-export/(?P<applicant_username>[^/]+)/?$', views.MentorContractExport.as_view(), name='mentor-contract'),
    url(r'^(?P<round_slug>[^/]+)/communities/(?P<community_slug>[^/]+)/(?P<project_slug>[^/]+)/final-application/fund/(?P<applicant_username>[^/]+)/(?P<funding>[^/]+)$', views.InternFund.as_view(), name='intern-fund'),
    url(r'^(?P<round_slug>[^/]+)/communities/(?P<community_slug>[^/]+)/(?P<project_slug>[^/]+)/final-application/organizer-approval/(?P<applicant_username>[^/]+)/(?P<approval>[^/]+)$', views.InternApprove.as_view(), name='intern-approval'),
    url(r'^(?P<round_slug>[^/]+)/communities/(?P<community_slug>[^/]+)/(?P<project_slug>[^/]+)/final-application/(?P<action>[^/]+)/(?:(?P<username>[^/]+)/)?$', views.FinalApplicationAction.as_view(), name='application-action'),
    url(r'^(?P<round_slug>[^/]+)/communities/(?P<community_slug>[^/]+)/(?P<project_slug>[^/]+)/final-application/rate/(?P<username>[^/]+)/(?P<rating>[^/]+)$', views.FinalApplicationRate.as_view(), name='application-rate'),
    url(r'^(?P<round_slug>[^/]+)/communities/(?P<community_slug>[^/]+)/(?P<project_slug>[^/]+)/contributions/add/$', views.ContributionUpdate.as_view(), name='contributions-add'),
    url(r'^(?P<round_slug>[^/]+)/communities/(?P<community_slug>[^/]+)/(?P<project_slug>[^/]+)/contributions/(?P<contribution_slug>[^/]+)/$', views.ContributionUpdate.as_view(), name='contributions-edit'),
    url(r'^(?P<round_slug>[^/]+)/communities/(?P<community_slug>[^/]+)/(?P<project_slug>[^/]+)/contributions/$', views.ProjectContributions.as_view(), name='contributions'),
    url(r'^(?P<round_slug>[^/]+)/communities/(?P<community_slug>[^/]+)/(?P<project_slug>[^/]+)/applicants/$', views.ProjectApplicants.as_view(), name='project-applicants'),
    url(r'^(?P<round_slug>[^/]+)/communities/(?P<community_slug>[^/]+)/applicants/$', views.community_applicants, name='community-applicants'),
    url(r'^(?P<round_slug>[^/]+)/communities/(?P<slug>[^/]+)/$', views.community_landing_view, name='community-landing'),
    url(r'^(?P<round_slug>[^/]+)/contract-export/$', views.contract_export_view, name='contract-export'),
    url(r'^intern-contract-export/$', views.intern_contract_export_view, name='intern-contract-export'),
    url(r'^generic-intern-contract-export/$', views.generic_intern_contract_export_view, name='generic-intern-contract-export'),
    url(r'^generic-mentor-contract-export/$', views.generic_mentor_contract_export_view, name='generic-mentor-contract-export'),
    url(r'^alums/$', views.alums_page, name='alums'),
    url(r'^communities/cfp/$', views.community_cfp_view, name='community-cfp'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^dashboard/trusted-volunteers/$', views.TrustedVolunteersListView.as_view(), name='trusted-volunteers-list'),
    url(r'^eligibility/$', views.EligibilityUpdateView.as_view(), name='eligibility'),
    url(r'^eligibility-results/$', views.EligibilityResults.as_view(), name='eligibility-results'),
    url(r'^email/application-deadline-review/$', views.MentorCheckDeadlinesReminder.as_view(), name='email-deadline-review'),
    url(r'^email/application-period-ended/$', views.ContributorsApplicationPeriodEndedReminder.as_view(), name='email-application-period-ended'),
    url(r'^email/application-deadline-reminder/$', views.ApplicantsDeadlinesReminder.as_view(), name='email-deadline-reminder'),
    url(r'^email/contributor-deadline-reminder/$', views.ContributorsDeadlinesReminder.as_view(), name='email-contributor-deadline-reminder'),
    url(r'^email/mentor-application-deadline-reminder/$', views.MentorApplicationDeadlinesReminder.as_view(), name='email-mentor-application-deadline-reminder'),
    url(r'^email/mentor-intern-selection-reminder/$', views.MentorInternSelectionReminder.as_view(), name='email-mentor-intern-selection-reminder'),
    url(r'^email/coordinator-intern-selection-reminder/$', views.CoordinatorInternSelectionReminder.as_view(), name='email-coordinator-intern-selection-reminder'),
    url(r'^email/intern-welcome/$', views.InternNotification.as_view(), name='email-intern-welcome'),
    url(r'^email/mentor-intern-start-reminder/$', views.MentorFirstPaymentNotification.as_view(), name='email-mentor-intern-start-reminder'),
    url(r'^longitudinal-survey/2018-initiate/$', views.Survey2018Notification.as_view(), name='longitudinal-survey-2018-initiate'),
    url(r'^longitudinal-survey/2018/(?P<survey_slug>[^/]+)/$', views.AlumSurveyUpdate.as_view(), name='longitudinal-survey-2018'),
    url(r'^longitudinal-survey/2018-completed/$', TemplateView.as_view(template_name='home/survey_confirmation.html'), name='longitudinal-survey-2018-completed'),
    url(r'^longitudinal-survey/2018-opt-out/(?P<survey_slug>[^/]+)/$', views.survey_opt_out, name='longitudinal-survey-2018-opt-out'),
    url(r'^account/$', views.ComradeUpdate.as_view(), name='account'),
    url(r'^apply/project-selection/$', views.current_round_page, name='project-selection'),
    url(r'^past-projects/$', views.past_rounds_page, name='past-rounds'),
    url(r'^apply/make-contributions/$', views.contribution_tips, name='contribution-tips'),
    url(r'^apply/eligibility/$', views.eligibility_information, name='eligibility-information'),
    url(r'^register/$', views.RegisterUser.as_view(), name='register'),
    url(r'^register/sent/$', views.PendingRegisterUser.as_view(), name='registration_complete'),
    url(r'^register/activate/(?P<activation_key>[-.:\w]+)/$', views.ActivationView.as_view(), name='registration_activate'),
    url(r'^register/activate/$', views.ActivationCompleteView.as_view(), name='registration_activation_complete'),
    url(r'^blog/(?P<round_slug>[^/]+)/application-period-statistics/$', views.round_statistics, name='blog-application-period-statistics'),
    url(r'^privacy-policy/$', views.privacy_policy, name='privacy-policy'),
]
