# Generated by Django 3.1.14 on 2022-12-26 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumsurveytracker',
            name='alumni_info',
        ),
        migrations.RemoveField(
            model_name='alumsurveytracker',
            name='intern_info',
        ),
        migrations.RemoveField(
            model_name='aluminfo',
            name='survey_opt_out',
        ),
        migrations.RemoveField(
            model_name='internselection',
            name='survey_opt_out',
        ),
        migrations.DeleteModel(
            name='AlumSurvey',
        ),
        migrations.DeleteModel(
            name='AlumSurveyTracker',
        ),
    ]
