# Generated by Django 3.2.16 on 2023-01-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comrade',
            name='mastodon_url',
            field=models.URLField(blank=True, help_text="(Optional) The full URL to your Mastodon profile.<br>For mentors and coordinators, this will be displayed to applicants, who may try to contact you via Mastodon. Applicants' Mastodon URLs will be shared with their mentors and coordinators. Accepted interns' Mastodon URLs will be displayed on the Outreachy website.", verbose_name='Mastodon profile URL'),
        ),
        migrations.AlterField(
            model_name='comrade',
            name='twitter_url',
            field=models.URLField(blank=True, help_text="(Optional) The full URL to your Twitter profile.<br>For mentors and coordinators, this will be displayed to applicants, who may try to contact you via Twitter. Applicants' Twitter URLs will be shared with their mentors and coordinators. Accepted interns' Twitter URLs will be displayed on the Outreachy website.", verbose_name='Twitter profile URL'),
        ),
    ]
