# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0039_collectionviewrestriction'),
        ('home', '0004_roundsindexpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('roundnumber', models.IntegerField()),
                ('applicationsopendate', models.DateField(verbose_name='Date applications open')),
                ('internshipstartdate', models.DateField(verbose_name='Date internships start')),
                ('internshipenddate', models.DateField(verbose_name='Date internships end')),
                ('sponsordetails', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
