# Generated by Django 3.2.16 on 2023-04-05 21:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230116_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=50)),
                ('notes', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='comrade',
            name='organizer_notes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.organizernotes'),
        ),
    ]
