# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 02:49
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_roundpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundpage',
            name='sponsordetails',
            field=wagtail.core.fields.RichTextField(default='<p>Outreachy is hosted by the <a href="https://sfconservancy.org/">Software Freedom Conservancy</a> with special support from Red Hat, GNOME, and <a href="http://otter.technology">Otter Tech</a>. We invite companies and free and open source communities to sponsor internships in the next round.'),
        ),
    ]
