# Generated by Django 4.2.9 on 2024-02-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_comrade_organizer_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayQualityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Essay quality category name', max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='essayquality',
            options={'ordering': ('category_name', 'description')},
        ),
        migrations.RenameField(
            model_name='essayquality',
            old_name='category',
            new_name='category_name',
        ),
    ]
