# Generated by Django 4.2.9 on 2024-02-23 01:07

from django.db import migrations, models
import django.db.models.deletion

def create_essay_quality_categories(apps, schema_editor):
    EssayQuality = apps.get_model('home.EssayQuality')
    EssayQualityCategory = apps.get_model('home.EssayQualityCategory')

    # Find all the (unique) category names currently in the database
    qualities = EssayQuality.objects.all()
    categories = list(set([q.category_name.lower().capitalize() for q in qualities]))

    # Create new category objects, and assign each essay quality a category
    for c in categories:
        category = EssayQualityCategory.objects.create(name=c)
        qualities_to_categorize = EssayQuality.objects.filter(category_name__iexact=c)
        for essay_quality in qualities_to_categorize:
            essay_quality.category = category
            essay_quality.save()

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_essayqualitycategory_alter_essayquality_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayquality',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.essayqualitycategory'),
        ),
        migrations.RunPython(create_essay_quality_categories),
    ]
