# Generated by Django 4.2.9 on 2024-02-23 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_essayquality_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='essayquality',
            options={'ordering': ('category__name', 'description')},
        ),
        migrations.RemoveField(
            model_name='essayquality',
            name='category_name',
        ),
        migrations.AlterField(
            model_name='essayquality',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.essayqualitycategory'),
        ),
    ]
