# Generated by Django 4.2.15 on 2025-01-22 17:38

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_essayquality_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100, validators=[home.models.skill_is_valid], verbose_name='Skill name')),
                ('experience_level', models.CharField(choices=[('CON', 'Concepts'), ('EXP', 'Exploring'), ('GRW', 'Growing'), ('IND', 'Independent')], default='CON', max_length=3, verbose_name='Experience level')),
                ('comrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.comrade', verbose_name='Comrade')),
            ],
        ),
    ]
