# Generated by Django 4.2.15 on 2025-01-27 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_essayquality_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='number_interns',
            field=models.PositiveIntegerField(default=0, help_text='How many interns will your community accept this internship cohort?', verbose_name='Number of interns'),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='donation_for_any_outreachy_internship',
            field=models.PositiveIntegerField(default=0, verbose_name='Donation amount ($ USD) for Outreachy internships'),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='donation_for_other',
            field=models.PositiveIntegerField(default=0, verbose_name='Donation amount ($ USD) for other'),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='donation_for_other_information',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='donation_for_outreachy_general_activities',
            field=models.PositiveIntegerField(default=0, verbose_name='Donation amount ($ USD) for Outreachy program activities'),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='due_date',
            field=models.DateField(default=datetime.date.today, help_text='Due date to provide an invoice to the sponsoring organization'),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='due_date_info',
            field=models.CharField(blank=True, help_text='Please provide any additional information about due dates for this sponsorship', max_length=800, verbose_name='Information about due dates'),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='sponsor_contact',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='sponsor_relationship',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='amount',
            field=models.PositiveIntegerField(default=0, help_text='Sponsorship for each intern is $6,500.', verbose_name='Sponsorship amount'),
        ),
    ]
