# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20170810_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundpage',
            name='applicationsopendate',
        ),
        migrations.RemoveField(
            model_name='roundpage',
            name='internshipenddate',
        ),
        migrations.RemoveField(
            model_name='roundpage',
            name='internshipstartdate',
        ),
        migrations.AddField(
            model_name='roundpage',
            name='appsclose',
            field=models.DateField(blank=True, default='2017-10-23', verbose_name='Date applications are due'),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='appslate',
            field=models.DateField(blank=True, default='2017-10-30', verbose_name='Date extended applications are due'),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='appsopen',
            field=models.DateField(default='2017-09-07', verbose_name='Date applications open'),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='finalfeedback',
            field=models.DateField(blank=True, default='2018-03-12', verbose_name='Date final feedback is due'),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='internends',
            field=models.DateField(default='2018-03-05', verbose_name='Date internships end'),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='internstarts',
            field=models.DateField(default='2017-12-05', verbose_name='Date internships start'),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='landingdue',
            field=models.DateField(blank=True, default='2017-08-28', verbose_name='Date community landing pages are due'),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='lateorgs',
            field=models.DateField(blank=True, default='2017-10-02', verbose_name='Last date to add community landing pages'),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='midfeedback',
            field=models.DateField(blank=True, default='2018-01-16', verbose_name='Date mid-point feedback is due'),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='orgreminder',
            field=models.DateField(blank=True, default='2017-08-14', verbose_name='Date to remind orgs to submit their home pages'),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='pingnew',
            field=models.DateField(blank=True, default='2017-08-01', verbose_name='Date to start pinging new orgs'),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='pingold',
            field=models.DateField(blank=True, default='2017-08-07', verbose_name='Date to start pinging past orgs'),
        ),
    ]
