# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20170811_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundpage',
            name='internannounce',
            field=models.DateField(default='2017-11-09', verbose_name='Date interns are announced'),
        ),
    ]
