# Generated by Django 4.2.15 on 2025-02-04 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_professionalskill'),
        ('home', '0012_sponsorship_coordinator_is_sponsor_rep_and_more'),
    ]

    operations = [
    ]
