# Generated by Django 4.2.15 on 2025-08-12 17:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_merge_20250204_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_policy',
            field=ckeditor.fields.RichTextField(blank=True, help_text="(Optional) Please describe your policy on the use of AI tools (e.g., ChatGPT, GitHub Copilot) for contributions to this project. Indicate whether AI-assisted code, documentation, or other work is permitted, prohibited, or allowed under specific conditions (e.g., with attribution or review). You may also link to your community's AI policy if one exists. This information will help applicants understand expectations during the contribution and internship periods.", verbose_name='AI tool usage policy'),
        ),
    ]
