# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20170821_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymentorinvite',
            name='role',
            field=models.CharField(choices=[('CO', 'This person is a coordinator. They are helping track mentors and find funding. Coordinators may also be mentors, and thus also have permissions to add or edit project pages.'), ('ME', "This person is a mentor. They need to add a project page or edit a co-mentor's project page."), ('RE', 'This person is an applicant reviewer. They will not be given access to modify the community page or add/modify project pages.')], default='ME', max_length=2),
        ),
    ]
