# Generated by Django 4.2.15 on 2026-08-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_project_ai_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrierstoparticipation',
            name='technical_task_or_project',
            field=models.TextField(default='', max_length=1000, verbose_name="Tell us about a technical task or project you've worked on. It could be anything from a class assignment or personal project. What did you enjoy about it and what was challenging? You are welcome to share links to your work if you have them. If you're very early in your career journey, tell us something technical you'd like to work on and what you have already done to start exploring it."),
        ),
    ]
