# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_communitymentorinvite_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymentorinvite',
            name='role',
            field=models.CharField(choices=[('CO', 'Coordinator. They are helping track mentors and find funding. Coordinators may also be mentors, and thus also have permissions to add or edit project pages.'), ('ME', "Mentor. They need to add a project page or edit a co-mentor's project page."), ('RE', 'Applicant reviewer. They will not be given access to modify the community page or add/modify project pages.')], default='ME', max_length=2),
        ),
    ]
