# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20171108_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluminfo',
            name='rss',
            field=models.URLField(blank=True, verbose_name='RSS URL (optional)'),
        ),
        migrations.AlterField(
            model_name='aluminfo',
            name='blog',
            field=models.URLField(blank=True, verbose_name='Blog URL (optional)'),
        ),
    ]
