# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 04:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('home', '0020_auto_20171128_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitymentorinvite',
            name='page',
        ),
        migrations.RemoveField(
            model_name='communitypage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='CommunityMentorInvite',
        ),
        migrations.DeleteModel(
            name='CommunityPage',
        ),
    ]
