# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-19 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20171218_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Community name')),
                ('description', models.CharField(max_length=800, verbose_name='Short description of community (3 sentences for someone who has never heard of your community or the technologies involved)')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interns_funded', models.IntegerField(verbose_name='How many interns do you expect to fund for this round? (Include any Outreachy community credits to round up to an integer number.)')),
                ('cfp_text', models.CharField(max_length=3000, verbose_name="Additional information to provide on a call for mentors and volunteers page (e.g. what kinds of projects you're looking for, ways for volunteers to help Outreachy applicants)")),
                ('cfp_open', models.BooleanField(verbose_name='Open call for mentors and volunteers?')),
                ('list_community', models.BooleanField(default=False, verbose_name='Organizers: Check this box once you have reviewed the community information, confirmed funding, and collected billing information')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Community')),
                ('participating_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.RoundPage')),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='rounds',
            field=models.ManyToManyField(through='home.Participation', to='home.RoundPage'),
        ),
    ]
