# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20171219_2252_squashed_0065_auto_20180110_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='longevity',
            field=models.CharField(choices=[('3M', '0-3 months'), ('6M', '3-6 months'), ('1Y', '6-12 months'), ('2Y', '1-2 years'), ('OL', 'More than 2 years')], default='3M', help_text='How long has the project accepted publicly submitted contributions?', max_length=2),
        ),
    ]
