# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20171219_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='cfp_open',
        ),
    ]
