# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 19:34
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify

def generate_slug(apps, schema_editor):
    Community = apps.get_model('home', 'Community')
    for c in Community.objects.all():
        # We check for None here, because that means that it's NULL in the database,
        # instead of being set to an empty string.
        if c.slug is None:
            c.slug = slugify(c.name)
            c.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_community_slug'),
    ]

    operations = [
        migrations.RunPython(generate_slug, reverse_code=migrations.RunPython.noop, elidable=True),
    ]
