# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20180111_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorapproval',
            name='longevity',
            field=models.CharField(choices=[('3M', '0-2 months'), ('6M', '3-5 months'), ('1Y', '6-11 months'), ('2Y', '1-2 years'), ('OL', 'More than 2 years')], default='3M', help_text='How long have you been contributing to this project?', max_length=2),
        ),
        migrations.AlterField(
            model_name='newcommunity',
            name='community_size',
            field=models.CharField(choices=[('3', '1-2 people'), ('5', '3-5 people'), ('10', '6-10 people'), ('20', '11-20 people'), ('50', '21-50 people'), ('100', '50-100 people'), ('999', 'More than 100 people')], default='3', help_text='How many people are contributing to this community regularly?', max_length=3),
        ),
        migrations.AlterField(
            model_name='newcommunity',
            name='longevity',
            field=models.CharField(choices=[('3M', '0-2 months'), ('6M', '3-5 months'), ('1Y', '6-11 months'), ('2Y', '1-2 years'), ('OL', 'More than 2 years')], default='3M', help_text='How long has the community been a free and open source software (FOSS) community?', max_length=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='community_size',
            field=models.CharField(choices=[('3', '1-2 people'), ('5', '3-5 people'), ('10', '6-10 people'), ('20', '11-20 people'), ('50', '21-50 people'), ('100', '50-100 people'), ('999', 'More than 100 people')], default='3', help_text='How many people are contributing to this project regularly?', max_length=3),
        ),
    ]
