# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 05:50
from __future__ import unicode_literals

from django.db import migrations

PENDING = 'P'
WITHDRAWN = 'W'
REJECTED = 'R'
APPROVED = 'A'

def infer_approval(apps, schema_editor):
    Participation = apps.get_model('home', 'Participation')
    for o in Participation.objects.iterator():
        if o.list_community is None:
            o.approval_status = PENDING
        elif o.list_community:
            o.approval_status = APPROVED
        elif o.reason_for_not_participating:
            o.approval_status = WITHDRAWN
            o.reason_denied = o.reason_for_not_participating
        else:
            o.approval_status = REJECTED
        o.save()

    Project = apps.get_model('home', 'Project')
    for o in Project.objects.iterator():
        if o.list_project is None:
            o.approval_status = PENDING
        elif o.list_project:
            o.approval_status = APPROVED
        else:
            o.approval_status = REJECTED
        o.save()

    MentorApproval = apps.get_model('home', 'MentorApproval')
    for o in MentorApproval.objects.iterator():
        if o.approved:
            o.approval_status = APPROVED
        else:
            o.approval_status = PENDING
        o.save()

    CoordinatorApproval = apps.get_model('home', 'CoordinatorApproval')
    for o in CoordinatorApproval.objects.iterator():
        if o.approved is None:
            o.approval_status = PENDING
        elif o.approved:
            o.approval_status = APPROVED
        else:
            o.approval_status = REJECTED
        o.save()

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20180111_0200_squashed_0027_auto_20180112_2120'),
    ]

    operations = [
        migrations.RunPython(infer_approval, reverse_code=migrations.RunPython.noop),
    ]
