# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='list_project',
            field=models.BooleanField(default=False, verbose_name='Coordinators: Check this box once you have reviewed the project information'),
        ),
        migrations.AlterField(
            model_name='project',
            name='approved_license',
            field=models.BooleanField(help_text='I assert that my project is released under an <a href="https://opensource.org/licenses/alphabetical">OSI-approved open source license</a> or a <a href="https://creativecommons.org/share-your-work/licensing-types-examples/">Creative Commons license</a>'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Participation', verbose_name='Outreachy round and community'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_title',
            field=models.CharField(help_text='Short project title. This should be 100 characters or less, starting with a verb like "Create", "Improve", "Extend", "Survey", "Document", etc. Assume the applicant has never heard of your technology before and keep it simple.', max_length=100),
        ),
    ]
