# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20171228_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_title',
            field=models.CharField(help_text='Short project title. This should be 100 characters or less, starting with a verb like "Create", "Improve", "Extend", "Survey", "Document", etc. Assume the applicant has never heard of your technology before and keep it simple.', max_length=100, unique=True),
        ),
    ]
