# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_refactor_approval_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinatorapproval',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='mentorapproval',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='list_community',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='reason_for_not_participating',
        ),
        migrations.RemoveField(
            model_name='project',
            name='list_project',
        ),
    ]
