# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 21:54
from __future__ import unicode_literals

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20180112_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comrade',
            name='pronouns',
            field=models.CharField(choices=[('she', 'she/her/her'), ('he', 'he/him/him'), ('they', 'they/them/their'), ('fae', 'fae/faer/faer'), ('ey', 'ey/em/eir'), ('per', 'per/per/pers'), ('ve', 've/ver/vis'), ('xe', 'xem/xyr/xyrs'), ('ze', 'hir/hir/hirs')], default=['they', 'them', 'their', 'theirs', 'themself', 'http://pronoun.is/they'], help_text="Your preferred pronoun. This will be used in emails from Outreachy organizers directly to you. The format is subject/object/possessive. Example: '__(subject)__ interned with Outreachy. The mentor liked working with __(object)__. __(possessive)__ internship project was challenging.", max_length=4, verbose_name='Pronouns'),
        ),
        migrations.AlterField(
            model_name='mentorapproval',
            name='communication_channel_username',
            field=models.CharField(blank=True, help_text='What is your username on the team communication channel? (This information will be shared with applicants.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='mentorapproval',
            name='longevity',
            field=models.CharField(choices=[('3M', '0-2 months'), ('6M', '3-5 months'), ('1Y', '6-11 months'), ('2Y', '1-2 years'), ('OL', 'More than 2 years')], default='3M', help_text='How long have you been a contributor on this team?', max_length=2),
        ),
        migrations.AlterField(
            model_name='mentorapproval',
            name='understands_applicant_time_commitment',
            field=models.BooleanField(default=False, help_text='I understand that Outreachy mentors often find they must spend more time helping applicants during the application period than helping their intern during the internship period'),
        ),
        migrations.AlterField(
            model_name='newcommunity',
            name='community_size',
            field=models.CharField(choices=[('3', '1-2 people'), ('5', '3-5 people'), ('10', '6-10 people'), ('20', '11-20 people'), ('50', '21-50 people'), ('100', '50-100 people'), ('999', 'More than 100 people')], default='3', help_text='How many people are contributing to this FOSS community regularly?', max_length=3),
        ),
        migrations.AlterField(
            model_name='newcommunity',
            name='longevity',
            field=models.CharField(choices=[('3M', '0-2 months'), ('6M', '3-5 months'), ('1Y', '6-11 months'), ('2Y', '1-2 years'), ('OL', 'More than 2 years')], default='3M', help_text='How long has this FOSS community accepted public contributions?', max_length=2),
        ),
        migrations.AlterField(
            model_name='newcommunity',
            name='participating_orgs',
            field=models.CharField(help_text='What different organizations and companies participate in this FOSS community?', max_length=3000),
        ),
        migrations.AlterField(
            model_name='newcommunity',
            name='unapproved_license_description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='(Optional) If your FOSS community uses a license that is not an OSI-approved and FSF-approved license OR a Creative Commons license, please provide a description and links to the non-free licenses.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='accepting_new_applicants',
            field=models.BooleanField(default=True, help_text='Is this internship project currently accepting contributions from new applicants? If you have an applicant in mind to accept as an intern (or several promising applicants) who have filled out the eligibility information and an application, you can uncheck this box to close the internship project to new applicants.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='approved_license',
            field=models.BooleanField(default=False, help_text='I assert that this Outreachy internship project will released under either an <a href="https://opensource.org/licenses/alphabetical">OSI-approved open source license</a> that is also identified by the FSF as a <a href="https://www.gnu.org/licenses/license-list.html">free software license</a>, OR a <a href="https://creativecommons.org/share-your-work/public-domain/freeworks/">Creative Commons license approved for free cultural works</a>'),
        ),
        migrations.AlterField(
            model_name='project',
            name='communication_help',
            field=models.URLField(blank=True, help_text='(Optional) URL for the documentation for your communication tool'),
        ),
        migrations.AlterField(
            model_name='project',
            name='communication_norms',
            field=ckeditor.fields.RichTextField(blank=True, help_text='(Optional) After following the communication channel link, are there any special instructions? For example: "Join the #outreachy Zulip channel and make sure to introduce yourself.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='communication_url',
            field=models.CharField(blank=True, help_text='(Optional) URL for the communication channel applicants will use to reach mentors and ask questions about this internship project. For IRC, use irc://<host>[:port]/[channel]. Since many applicants have issues with IRC port blocking at their universities, IRC communication links will use <a href="https://kiwiirc.com/">Kiwi IRC</a> to embed the IRC communications in the project page.', max_length=200, validators=[django.core.validators.URLValidator(schemes=['http', 'https', 'irc'])]),
        ),
        migrations.AlterField(
            model_name='project',
            name='community_benefits',
            field=models.CharField(blank=True, help_text='How will this internship project benefit the FOSS community that is funding it?', max_length=800),
        ),
        migrations.AlterField(
            model_name='project',
            name='community_size',
            field=models.CharField(choices=[('3', '1-2 people'), ('5', '3-5 people'), ('10', '6-10 people'), ('20', '11-20 people'), ('50', '21-50 people'), ('100', '50-100 people'), ('999', 'More than 100 people')], default='3', help_text='How many regular contributors does this team have?', max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='issue_tracker',
            field=models.URLField(blank=True, help_text="(Optional) URL for your team's issue tracker"),
        ),
        migrations.AlterField(
            model_name='project',
            name='long_description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Description of the internship project, excluding applicant skills.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='longevity',
            field=models.CharField(choices=[('3M', '0-3 months'), ('6M', '3-6 months'), ('1Y', '6-12 months'), ('2Y', '1-2 years'), ('OL', 'More than 2 years')], default='3M', help_text="How long has the team accepted publicly submitted contributions? (See the 'Terms Used' section above for a definition of a team.", max_length=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='newcomer_issue_tag',
            field=models.CharField(blank=True, help_text='(Optional) What tag is used for newcomer-friendly issues for your team or for this internship project?', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='repository',
            field=models.URLField(blank=True, help_text="(Optional) URL for your team's repository or contribution mechanism"),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_title',
            field=models.CharField(help_text='Short title for this internship project proposal. This should be 100 characters or less, starting with a verb like "Create", "Improve", "Extend", "Survey", "Document", etc. Assume the applicant has never heard of your technology before and keep it simple. The short title will be used in your project page URL, so keep it short.', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(verbose_name='Project URL slug'),
        ),
        migrations.AlterField(
            model_name='projectskill',
            name='experience_level',
            field=models.CharField(choices=[('WTU', 'Mentors are willing to teach this skill to applicants with no experience at all'), ('CON', 'Applicants should have read about the skill'), ('EXP', 'Applicants should have used this skill in class or personal projects'), ('FAM', 'Applicants should be able to expand on their skills with the help of mentors'), ('CHA', 'Applicants who are experienced in this skill will have the chance to expand it further')], default='WTU', help_text='Choose this carefully! Many Outreachy applicants choose not to apply for an internship project unless they meet 100% of the project skill criteria.', max_length=3, verbose_name='Expected skill experience level'),
        ),
        migrations.AlterField(
            model_name='projectskill',
            name='required',
            field=models.CharField(choices=[('BON', 'It would be nice if applicants had this skill, but it will not impact intern selection'), ('OPT', 'Mentors will prefer applicants who have this skill'), ('STR', 'Mentors will only accept applicants who have this skill as an intern')], default='BON', help_text='Is this skill a hard requirement, a preference, or an optional bonus? Choose this carefully! Many Outreachy applicants choose not to apply for an internship project unless they meet 100% of the project skill criteria.', max_length=3, verbose_name='Skill impact on intern selection'),
        ),
        migrations.AlterField(
            model_name='projectskill',
            name='skill',
            field=models.CharField(help_text='What is one skill an the applicant needs to have in order to contribute to this internship project, or what skill will they need to be willing to learn?', max_length=100, verbose_name='Skill description'),
        ),
    ]
