# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20180125_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantapproval',
            name='over_18',
            field=models.BooleanField(help_text='Will you be 18 years or older when the Outreachy internship period starts?'),
        ),
    ]
