# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-12 18:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20180125_1931_squashed_0067_auto_20180210_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorinformation',
            name='typical_hours',
            field=models.IntegerField(help_text='During the past three months, what is the average number of hours/week you have spent on contracted work and unpaid business development or business marketing? You will be able to enter your known contract hours for the Outreachy internship period on the next page.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Average number of hours spent on contractor business'),
        ),
        migrations.AlterField(
            model_name='employmenttimecommitment',
            name='hours_per_week',
            field=models.IntegerField(help_text='Number of hours per week required by your employment contract', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='schooltimecommitment',
            name='outreachy_credits',
            field=models.PositiveIntegerField(help_text='If you are going to seek university credit for your Outreachy internship, how many credits will you earn?', verbose_name='Number of internship or project credits for Outreachy'),
        ),
        migrations.AlterField(
            model_name='schooltimecommitment',
            name='registered_credits',
            field=models.IntegerField(help_text="What is the total number of credits you are enrolled for this term?<br>If you aren't registered yet, please provide an approximate number of credits?", validators=[django.core.validators.MinValueValidator(1)], verbose_name="Number of credits you're registered for"),
        ),
        migrations.AlterField(
            model_name='schooltimecommitment',
            name='thesis_credits',
            field=models.PositiveIntegerField(help_text='If you are a graduate student, how many credits will you earn for working on your thesis or research (not including the credits earned for the Outreachy internship)?', verbose_name='Number of graduate thesis or research credits'),
        ),
        migrations.AlterField(
            model_name='schooltimecommitment',
            name='typical_credits',
            field=models.IntegerField(help_text='How many credits does a typical student register for?<br> If your university has different credit requirements for each semester for students in your major, use the number of credits that are listed on your syllabus or class schedule.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of credits for a typical student'),
        ),
        migrations.AlterField(
            model_name='volunteertimecommitment',
            name='hours_per_week',
            field=models.IntegerField(help_text='Maximum hours per week spent volunteering.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
