# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 03:34
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify

def generate_slug(apps, schema_editor):
    Project = apps.get_model('home', 'Project')
    for p in Project.objects.all():
        # We check for None here, because that means that it's NULL in the database,
        # instead of being set to an empty string.
        if p.slug is None:
            p.slug = slugify(p.short_title)
            p.save(update_fields=['slug'])

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20171230_0334'),
    ]

    operations = [
        migrations.RunPython(generate_slug, reverse_code=migrations.RunPython.noop, elidable=True),
    ]
