# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-12 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20180212_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalapplication',
            name='applying_to_gsoc',
            field=models.TextField(blank=True, help_text="If you are a student at an accredited university or college, we highly encourage you to also apply to Google Summer of Code during the May to August internship round. Many Outreachy communities participate in both programs, and applying to Google Summer of Code increases your chances of being accepted. Please note that Google Summer of Code has stipend amounts that vary per country.<br><br>Please keep the list of communities and projects you're applying to under Google Summer of Code up-to-date, since we often try to coordinate with Google Summer of Code mentors during the intern selection period.<br><br>If this application is for the December to March internship period, or you're not applying to Google Summer of Code, please leave this question blank.", max_length=8000, verbose_name='(Optional) Please describe which Google Summer of Code communities and projects you are applying for'),
        ),
    ]
