# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20171230_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Community URL slug: https://www.outreachy.org/communities/SLUG/'),
        ),
    ]
