# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20180113_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='longevity',
            field=models.CharField(choices=[('3M', '0-2 months'), ('6M', '3-5 months'), ('1Y', '6-11 months'), ('2Y', '1-2 years'), ('OL', 'More than 2 years')], default='3M', help_text="How long has the team accepted publicly submitted contributions? (See the 'Terms Used' section above for a definition of a team.", max_length=2),
        ),
    ]
