# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20180125_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantapproval',
            old_name='us_santioned_country',
            new_name='us_sanctioned_country',
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='over_18',
            field=models.BooleanField(default=False, help_text='Will you be 18 years or older when the Outreachy internship period starts?'),
        ),
    ]
