# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20171230_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='accepting_new_applicants',
            field=models.BooleanField(default=True, help_text='Is this project currently accepting new applicants? If you have an applicant in mind to accept as an intern (or several promising applicants) who have filled out the eligibility information and an application, you can uncheck this box to close the project to new applicants.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Community URL slug: https://www.outreachy.org/communities/SLUG/'),
        ),
    ]
