# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-13 19:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20180213_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantapproval',
            name='enrolled_as_noncollege_student',
            field=models.NullBooleanField(help_text='Will you be enrolled in a coding school or self-paced online classes during the Outreachy internship period? If you are taking classes without receiving credits, select this option.', verbose_name='Are you enrolled in a coding school or self-paced online courses?'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='enrolled_as_student',
            field=models.NullBooleanField(help_text='Will you be enrolled in a university or college during the Outreachy internship period? University and college students will be asked questions about the number of credits they are taking.', verbose_name='Are you a university or college student?'),
        ),
        migrations.AlterField(
            model_name='noncollegeschooltimecommitment',
            name='description',
            field=models.TextField(blank=True, help_text='Please describe the course. Include the name and a link to the website of your coding school or organization offering online courses. Add the course name and a short description of course work.', max_length=3000),
        ),
        migrations.AlterField(
            model_name='noncollegeschooltimecommitment',
            name='hours_per_week',
            field=models.IntegerField(help_text='Maximum hours per week spent on coursework, exercises, homework, and studying for this course.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
