# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-15 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20180213_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalapplication',
            name='spread_the_word',
            field=models.CharField(choices=[('BIT', 'From the Blacks in Tech job board'), ('WITCH', 'From the Women in Tech Chat slack'), ('LGBTQ', 'From the LGBTQ in Tech slack'), ('WIL', 'From the Women in Linux group'), ('H4CK', 'From Trans*H4CK'), ('LAIT', 'From the Latinas in Tech group'), ('GWC', 'From the Girls Who Code job board'), ('WWC', 'From the Women Who Code job board'), ('NAJ', 'From the Native American Jobs board'), ('POCIT', 'From the POCIT jobs board'), ('RC', 'From the Recurse Center Zulip chat'), ('HYP', 'From the Hypatia Software slack channel'), ('PRES', 'From a presentation by an Outreachy organizer'), ('TAPIA', 'At the Richard Tapia conference'), ('CONF', 'At another conference'), ('ALUM', 'From a former Outreachy intern'), ('MENT', 'From an Outreachy mentor'), ('TEACH', 'From a teacher'), ('STUD', 'From a classmate'), ('PAL', 'From a friend'), ('TWIT', 'From Twitter'), ('SEAR', 'Found Outreachy from a web search'), ('OTH', 'Other')], default='OTH', max_length=5, verbose_name='How did you find out about Outreachy? (This will only be displayed to Outreachy Organizers.)'),
        ),
    ]
