# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-01 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20171231_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='list_community',
            field=models.NullBooleanField(default=None, verbose_name='Organizers: Check this box once you have reviewed the community information, confirmed funding, and collected billing information'),
        ),
    ]
