# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20180125_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantapproval',
            name='genderqueer',
            field=models.NullBooleanField(help_text='Do you identify as genderqueer, gender non-conforming, gender diverse, gender varient, or gender expansive, or are you questioning whether you identify with any of those terms?'),
        ),
    ]
