# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20180114_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcommunity',
            name='participating_orgs',
            field=models.CharField(help_text='What different organizations and companies participate in this FOSS community? If there are many organizations, list the top five organizations who make large contributions.', max_length=3000),
        ),
    ]
