# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-01 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20180101_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='reason_for_not_participating',
            field=models.CharField(blank=True, max_length=3000, verbose_name="Please let us know why your community won't be participating in this Outreachy round, and if there's anything the Outreachy organizers can do to help."),
        ),
    ]
