# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20180125_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantapproval',
            name='agender',
            field=models.NullBooleanField(help_text='I am demi-agender'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='androgyne',
            field=models.NullBooleanField(help_text='I am androgyne'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='androgynous',
            field=models.NullBooleanField(help_text='I am androgynous'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='aporagender',
            field=models.NullBooleanField(help_text='I am aporagender'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='bi_gender',
            field=models.NullBooleanField(help_text='I am bi-gender'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='demi_boy',
            field=models.NullBooleanField(help_text='I am a demi-boy'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='demi_gender',
            field=models.NullBooleanField(help_text='I am demi-gender'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='demi_genderfluid',
            field=models.NullBooleanField(help_text='I am demi-genderfluid'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='demi_girl',
            field=models.NullBooleanField(help_text='I am a demi-girl'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='demi_non_binary',
            field=models.NullBooleanField(help_text='I am demi-non-binary'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='gender_confusion',
            field=models.NullBooleanField(help_text='I am a gender confusion/Gender f*ck'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='gender_indifferent',
            field=models.NullBooleanField(help_text='I am gender indifferent'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='gender_neutral',
            field=models.NullBooleanField(help_text='I am gender neutral'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='genderfluid',
            field=models.NullBooleanField(help_text='I am genderfluid'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='genderflux',
            field=models.NullBooleanField(help_text='I am genderflux'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='genderless',
            field=models.NullBooleanField(help_text='I am genderless'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='graygender',
            field=models.NullBooleanField(help_text='I am graygender'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='intergender',
            field=models.NullBooleanField(help_text='I am intergender'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='man',
            field=models.NullBooleanField(help_text='I am a man'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='mavrique',
            field=models.NullBooleanField(help_text='I am a mavrique'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='maxigender',
            field=models.NullBooleanField(help_text='I am maxigender'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='multigender',
            field=models.NullBooleanField(help_text='I am multigender or polygender'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='neutrois',
            field=models.NullBooleanField(help_text='I am a neutrois'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='non_binary',
            field=models.NullBooleanField(help_text='I am non-binary'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='pangender',
            field=models.NullBooleanField(help_text='I am pangender or omnigender'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='tri_gender',
            field=models.NullBooleanField(help_text='I am tri-gender'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='woman',
            field=models.NullBooleanField(help_text='I am a woman'),
        ),
    ]
