# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-14 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20180114_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='notify_me',
            field=models.ManyToManyField(to='home.Comrade'),
        ),
    ]
