# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_community_notify_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_signup', models.DateField(default='2017-11-09', verbose_name='Date user signed up for notifications')),
            ],
        ),
        migrations.RemoveField(
            model_name='community',
            name='notify_me',
        ),
        migrations.AddField(
            model_name='notification',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Community'),
        ),
        migrations.AddField(
            model_name='notification',
            name='comrade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Comrade'),
        ),
    ]
