# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20180125_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantapproval',
            name='eligible_to_work',
            field=models.NullBooleanField(help_text='Are you eligible to work for 40 hours a week in the country you will be living in during the Outreachy internship period?</p><p>Student visas: Please note that in some countries, students studying abroad on a student visa may not be eligible to work full-time (40 hours a week). If you are on a student visa, please double check with your school counselors before applying.</p><p>Spouse visas: In some countries, spousal visas may not allow spouses to work. Please contact your immigration officer if you have any questions about whether your visa will be impacted by full-time work (40 hours a week).'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='genderqueer',
            field=models.NullBooleanField(help_text='Do you identify as genderqueer, gender non-conforming, gender diverse, gender varient, or gender expansive? If you are questioning whether you identify with any of those terms, please say yes.', verbose_name='Do you identify as genderqueer?'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='gsoc_or_outreachy_internship',
            field=models.NullBooleanField(help_text='Have you been accepted as a Google Summer of Code intern or an Outreachy intern before? Please say yes even if you did not complete the internship.', verbose_name='Previous Google Summer of Code or Outreachy internship?'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='over_18',
            field=models.NullBooleanField(help_text='Will you be 18 years or older when the Outreachy internship starts?', verbose_name='Are you over 18 years of age?'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='transgender',
            field=models.NullBooleanField(help_text='If you are questioning whether you are transgender, please say yes.', verbose_name='Do you identify as transgender?'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='under_export_control',
            field=models.NullBooleanField(help_text='Are you a person or entity restricted by US export controls or sanctions programs? If you are unsure what those terms mean, answer no.'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='us_national_or_permanent_resident',
            field=models.NullBooleanField(help_text='Are you a national or permanent resident of the United States of America? Outreachy in open to people around the world, but we need to ask additional questions for U.S. residents.'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='us_resident_demographics',
            field=models.NullBooleanField(verbose_name='Are you Black/African American, Hispanic/Latin@, Native American, Alaska Native, Native Hawaiian, or Pacific Islander?'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='us_sanctioned_country',
            field=models.NullBooleanField(help_text='If you have citizenship with of one of these counties, please answer yes, even if you are not currently living in those countries.', verbose_name='Are you a citizen, resident, or national of Crimea, Cuba, Iran, North Korea, or Syria?'),
        ),
    ]
