# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-01 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_participation_reason_for_not_participating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='reason_for_not_participating',
            field=models.CharField(blank=True, max_length=3000, verbose_name="Please let Outreachy organizers know why your community won't be participating in this Outreachy round, and if there's anything we can do to help. This private information is only used by the Outreachy organizers, and will not be displayed on your community page."),
        ),
    ]
