# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-19 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20180215_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantapproval',
            name='rating',
            field=models.CharField(choices=[('AMZ', '5 - Amazing - multiple large, high-quality contributions'), ('STR', '4 - Strong - at least one large, high-quality contribution'), ('GD', '3 - Good - some smaller contributions of good quality'), ('UN', '2 - Inexperienced - smaller contributions that vary in quality'), ('NGD', '1 - Struggling - applicant did not understand instructions or feedback')], default='GD', max_length=3),
        ),
    ]
