# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20180115_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_of_signup',
            field=models.DateField(auto_now_add=True, verbose_name='Date user signed up for notifications'),
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set([('community', 'comrade')]),
        ),
    ]
