# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20180101_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_size', models.CharField(choices=[('3', '1-3 people'), ('5', '3-5 people'), ('10', '5-10 people'), ('20', '11-20 people'), ('50', '21-50 people'), ('100', '50-100 people'), ('999', 'More than 100 people')], default='3', help_text='How many people are contributing to this community regularly?', max_length=3)),
                ('longevity', models.CharField(choices=[('3M', '0-3 months'), ('6M', '3-6 months'), ('1Y', '6-12 months'), ('2Y', '1-2 years'), ('OL', 'More than 2 years')], default='3M', help_text='How long has the community been a free and open source software (FOSS) community?', max_length=2)),
                ('participating_orgs', models.CharField(help_text='What different organizations and companies participate in the project?', max_length=3000)),
                ('approved_license', models.BooleanField(help_text='I assert that all Outreachy projects under my community will be released under an <a href="https://opensource.org/licenses/alphabetical">OSI-approved open source license</a> or a <a href="https://creativecommons.org/share-your-work/licensing-types-examples/">Creative Commons license</a>')),
                ('unapproved_license_description', models.CharField(help_text='(Optional) If your community uses a license that is not an OSI-approved license or a Creative Commons license, please provide links to the licenses or a description.', max_length=3000)),
                ('no_proprietary_software', models.BooleanField(help_text='I assert all Outreachy projects under my community will not rely or build upon proprietary software.')),
                ('proprietary_software_description', models.CharField(help_text='(Optional) If your community relies or builds upon proprietary software, please provide description of what software is used.', max_length=3000)),
                ('goverance', models.URLField(blank=True, help_text="(Optional) Please provide a URL for a description of your community's governance model")),
                ('code_of_conduct', models.URLField(blank=True, help_text="(Optional) Please provide a URL for to your community's Code of Conduct")),
                ('cla', models.URLField(blank=True, help_text="(Optional) Please provide a URL for your community's Contributor License Agreement (CLA)")),
                ('dco', models.URLField(blank=True, help_text="(Optional) Please provide a URL for your community's Developer Certificate of Origin (DCO) agreement")),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Community')),
            ],
        ),
    ]
