# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20180126_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooltimecommitment',
            name='term_number',
            field=models.IntegerField(help_text='(Optional) If your university uses term numbers (e.g. 7th term), enter your current term number.'),
        ),
    ]
