# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20180115_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='cfp_text',
            field=models.CharField(blank=True, max_length=3000, verbose_name="Additional information to provide on a call for mentors and volunteers page (e.g. what kinds of internship projects you're looking for, ways for volunteers to help Outreachy applicants)"),
        ),
    ]
