# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20180126_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooltimecommitment',
            name='term_number',
        ),
        migrations.AlterField(
            model_name='schooltimecommitment',
            name='term_name',
            field=models.CharField(help_text='If your university uses term names (e.g. Winter 2018 term of your Sophomore year), enter your current term name, year in college, and term year. If your university uses term numbers (e.g. 7th semester), enter the term number.', max_length=100),
        ),
    ]
