# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-21 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20180220_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantapproval',
            name='rating',
        ),
        migrations.AddField(
            model_name='finalapplication',
            name='rating',
            field=models.CharField(choices=[('5', '5 - Amazing - multiple large, high-quality contributions'), ('4', '4 - Strong - at least one large, high-quality contribution'), ('3', '3 - Good - some smaller contributions of good quality'), ('2', '2 - Inexperienced - smaller contributions that vary in quality'), ('1', '1 - Struggling - applicant did not understand instructions or feedback'), ('0', 'Not rated')], default='0', max_length=1),
        ),
    ]
