# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20180102_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcommunity',
            name='community',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Community'),
        ),
    ]
