# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20180115_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorapproval',
            name='instructions_read',
            field=models.BooleanField(default=False, help_text='I have read the <a href="/mentor/#mentor">mentor duties</a> and <a href="/mentor/mentor-faq/">mentor FAQ</a>.', validators=[home.models.mentor_read_instructions]),
        ),
        migrations.AlterField(
            model_name='mentorapproval',
            name='understands_applicant_time_commitment',
            field=models.BooleanField(default=False, help_text='I understand that Outreachy mentors often find they must spend more time helping applicants during the application period than helping their intern during the internship period', validators=[home.models.mentor_read_instructions]),
        ),
        migrations.AlterField(
            model_name='mentorapproval',
            name='understands_intern_time_commitment',
            field=models.BooleanField(default=False, help_text='I understand that Outreachy mentors will spend a minimum of 5 hours a week mentoring their intern during the three month internship period', validators=[home.models.mentor_read_instructions]),
        ),
        migrations.AlterField(
            model_name='mentorapproval',
            name='understands_mentor_contract',
            field=models.BooleanField(default=False, help_text='I understand that Outreachy mentors will need to sign a <a href="/documents/1/Outreachy-Program--Mentorship-Terms-of-Participation-May-2017.pdf">mentor contract</a> after they accept an applicant as an intern', validators=[home.models.mentor_read_contract]),
        ),
    ]
