# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20180126_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorinformation',
            name='continuing_contract_work',
            field=models.NullBooleanField(verbose_name='Will you be doing contract work during the Outreachy internship period?'),
        ),
    ]
