# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-29 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20180126_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmenttimecommitment',
            name='quit_on_acceptance',
            field=models.NullBooleanField(help_text='I will quit this job or contract if I am accepted as an Outreachy intern.'),
        ),
    ]
