# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20180115_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='intern_tasks',
            field=models.CharField(blank=True, help_text='(Optional) Description of possible internship tasks.', max_length=800),
        ),
        migrations.AlterField(
            model_name='project',
            name='community_benefits',
            field=models.CharField(blank=True, help_text='(Optional) How will this internship project benefit the FOSS community that is funding it?', max_length=800),
        ),
        migrations.AlterField(
            model_name='project',
            name='intern_benefits',
            field=models.CharField(blank=True, help_text="(Optional) How will the intern benefit from working with your team on this project? Imagine you're pitching this internship to a promising candidate. What would you say to convince them to apply? For example, what technical and non-technical skills will they learn from working on this project? How will this help them further their career in open source?", max_length=800),
        ),
    ]
