# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-08 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20180308_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.CharField(choices=[('NOW', 'Immediately close this project to new applicants'), ('REG', 'Open applications until the application period ends'), ('LAT', 'Extend applications through the late application deadline')], help_text="If you have too many applicants, and your most promising applicants have recorded both a contribution and a final application, you may want to close your project to new applicants.<br>If you have too few applicants, you may want to extend your project's application deadline by one week.", max_length=3, null=True, verbose_name='Project application status'),
        ),
    ]
