# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-08 23:31
from __future__ import unicode_literals

from django.db import migrations

CLOSED = 'NOW'
ONTIME = 'REG'

def copy_deadline(apps, schema_editor):
    Project = apps.get_model('home', 'Project')
    for p in Project.objects.all():
        if p.accepting_new_applicants:
            p.deadline = ONTIME
        else:
            p.deadline = CLOSED
        p.save(update_fields=['deadline'])

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_project_deadline'),
    ]

    operations = [
            migrations.RunPython(copy_deadline, reverse_code=migrations.RunPython.noop),
    ]
