# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-29 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_employmenttimecommitment_quit_on_acceptance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenttimecommitment',
            name='end_date',
            field=models.DateField(help_text='End date of employment period. Use YYYY-MM-DD format.'),
        ),
        migrations.AlterField(
            model_name='employmenttimecommitment',
            name='start_date',
            field=models.DateField(help_text='Start date of employment period. Use YYYY-MM-DD format.'),
        ),
        migrations.AlterField(
            model_name='schooltimecommitment',
            name='end_date',
            field=models.DateField(help_text='This is the date your university advertises for the last possible date of any exam for any student in your semester. Use the last possible exam date, even if your personal exams end sooner.', verbose_name='Date all exams end. Use YYYY-MM-DD format.'),
        ),
        migrations.AlterField(
            model_name='schooltimecommitment',
            name='start_date',
            field=models.DateField(help_text='What is the first possible day of classes for all students?<br>If you started this term late (or will start this term late), use the date that classes start for all students, not the late registration date.<br>If students who are in different school years or different semester numbers start classes on different dates, use the first possible date that students in your year or semester start classes.<br>If you do not know when the term will start, use the start date of that term from last year.', verbose_name='Date classes start. Use YYYY-MM-DD format.'),
        ),
        migrations.AlterField(
            model_name='timecommitment',
            name='end_date',
            field=models.DateField(help_text='Date your time commitment ends. Use YYYY-MM-DD format.'),
        ),
        migrations.AlterField(
            model_name='timecommitment',
            name='start_date',
            field=models.DateField(help_text='Date your time commitment starts. Use YYYY-MM-DD format.'),
        ),
    ]
