# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 01:48
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20180115_0406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinator_can_update', models.BooleanField(help_text='\n            Can a community coordinator update this information, or is\n            it provided by the Outreachy organizers?\n            ')),
                ('name', models.CharField(help_text='The full sponsor name to be used on invoices.', max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('funding_secured', models.BooleanField(default=False, help_text='\n            Is this funding confirmed by the sponsoring organization, or\n            is it currently only tentative?\n            ')),
                ('funding_decision_date', models.DateField(default=datetime.date.today, help_text='Date by which you will know if this funding is confirmed.')),
                ('additional_information', ckeditor.fields.RichTextField(blank=True, help_text='\n            Anything else the Outreachy organizers should know about\n            this sponsorship.\n            ')),
            ],
        ),
        migrations.RemoveField(
            model_name='participation',
            name='cfp_text',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='interns_funded',
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Participation'),
        ),
    ]
