# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20180129_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenttimecommitment',
            name='quit_on_acceptance',
            field=models.BooleanField(help_text='I will quit this job or contract if I am accepted as an Outreachy intern.'),
        ),
    ]
