# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_comrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Comrade')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='mentors',
            field=models.ManyToManyField(through='home.MentorApproval', to='home.Comrade'),
        ),
    ]
