# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20180115_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedsponsorchange',
            name='log_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date coordinator made sponsorship change'),
        ),
    ]
