# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-09 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20180309_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='needs_more_applicants',
            field=models.BooleanField(default=False, help_text='Advertise this project as needing more applicants.'),
        ),
    ]
