# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20180105_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_title',
            field=models.CharField(help_text='Short project title. This should be 100 characters or less, starting with a verb like "Create", "Improve", "Extend", "Survey", "Document", etc. Assume the applicant has never heard of your technology before and keep it simple.', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(verbose_name='Community URL slug: https://www.outreachy.org/communities/SLUG/'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('slug', 'project_round')]),
        ),
    ]
