# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-20 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_project_needs_more_applicants'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('W', 'Withdrawn'), ('R', 'Rejected')], default='W', max_length=1)),
                ('reason_denied', models.CharField(blank=True, help_text='\n            Please explain why you are withdrawing this request. This\n            explanation will only be shown to Outreachy organizers and\n            approved people within this community.\n            ', max_length=3000)),
                ('funding_source', models.CharField(choices=[('GEN', 'Funded by the Outreachy general fund'), ('ORG', 'Funded by the community sponsors'), ('NOT', 'Not funded (intern will not be selected for this round)'), ('UND', 'Funding source undecided')], default='UND', help_text='How will this intern be funded?', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MentorRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SignedContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100000, verbose_name='Contract text')),
                ('legal_name', models.CharField(help_text='Your name on your government identification. This is the name that you would use to sign a legal document.', max_length=800, verbose_name='Legal name')),
                ('ip_address', models.GenericIPAddressField()),
                ('date_signed', models.DateField(verbose_name='Date contract was signed in YYYY-MM-DD format')),
            ],
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='self_identify',
            field=models.CharField(blank=True, help_text="If your gender identity is NOT listed above, what is your gender identity? Please note that 'gender identity' is NOT your name. Gender identity is your gender.", max_length=100),
        ),
        migrations.AddField(
            model_name='mentorrelationship',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.SignedContract'),
        ),
        migrations.AddField(
            model_name='mentorrelationship',
            name='intern_selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.InternSelection'),
        ),
        migrations.AddField(
            model_name='mentorrelationship',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.MentorApproval'),
        ),
        migrations.AddField(
            model_name='internselection',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ApplicantApproval'),
        ),
        migrations.AddField(
            model_name='internselection',
            name='intern_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SignedContract'),
        ),
        migrations.AddField(
            model_name='internselection',
            name='mentors',
            field=models.ManyToManyField(through='home.MentorRelationship', to='home.MentorApproval'),
        ),
        migrations.AddField(
            model_name='internselection',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='mentorrelationship',
            unique_together=set([('intern_selection', 'mentor')]),
        ),
    ]
