# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-21 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20180320_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internselection',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='internselection',
            name='reason_denied',
        ),
        migrations.AddField(
            model_name='internselection',
            name='organizer_approved',
            field=models.BooleanField(default=False, help_text='Is this intern and funding information confirmed to be correct by the Outreachy organizers?'),
        ),
    ]
