# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20180131_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantapproval',
            name='eligible_to_work',
            field=models.NullBooleanField(help_text='Are you eligible to work for 40 hours a week in the country (or countries) you will be living in during the Outreachy internship period?</p><p>Student visas: Please note that in some countries, students studying abroad on a student visa may not be eligible to work full-time (40 hours a week). If you are on a student visa, please double check with your school counselors before applying.</p><p>Spouse visas: In some countries, spousal visas may not allow spouses to work. Please contact your immigration officer if you have any questions about whether your visa allows you to work full-time (40 hours a week).'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='employed',
            field=models.NullBooleanField(help_text='Will you be an employee (for any number of hours) during the Outreachy internship period?'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='living_in_us',
            field=models.NullBooleanField(help_text='Please answer yes even if you are a citizen of a country other than USA.', verbose_name='Will you be living for the majority of the Outreachy internship period in the United States of America and be eligible to work in the U.S.A?'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='over_18',
            field=models.NullBooleanField(verbose_name='Will you be 18 years or older when the Outreachy internship starts?'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='under_export_control',
            field=models.NullBooleanField(verbose_name='Are you a person or entity restricted by <a href="https://www.treasury.gov/resource-center/sanctions/Programs/Pages/Programs.aspx">US export controls or sanctions programs</a>?'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='us_national_or_permanent_resident',
            field=models.NullBooleanField(help_text='Are you a national or permanent resident of the United States of America? Outreachy is open to some people around the world, and additional grpous of people in the U.S.A.'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='us_sanctioned_country',
            field=models.NullBooleanField(help_text='If you have citizenship with Cuba, Iran, North Korea, or Syria, please answer yes, even if you are not currently living in those countries.', verbose_name='Are you a citizen, resident, or national of Crimea, Cuba, Iran, North Korea, or Syria?'),
        ),
        migrations.AlterField(
            model_name='contractorinformation',
            name='typical_hours',
            field=models.IntegerField(help_text='During the past three months, what is the average number of hours/week you have spent on contracted work and unpaid business development or business marketing? You will be able to enter your known contract hours for the Outreachy internship period on the next page.', verbose_name='Average number of hours spent on contractor business'),
        ),
        migrations.AlterField(
            model_name='schooltimecommitment',
            name='outreachy_credits',
            field=models.IntegerField(help_text='If you are going to seek university credit for your Outreachy internship, how many credits will you earn?', verbose_name='Number of internship or project credits for Outreachy'),
        ),
        migrations.AlterField(
            model_name='schooltimecommitment',
            name='term_name',
            field=models.CharField(help_text='If your university uses term names (e.g. Winter 2018 term of your Sophomore year), enter your current term name, year in college, and term year. If your university uses term numbers (e.g. 7th semester), enter the term number.', max_length=100, verbose_name='Term name or term number'),
        ),
        migrations.AlterField(
            model_name='schooltimecommitment',
            name='thesis_credits',
            field=models.IntegerField(help_text='If you are a graduate student, how many credits will you earn for working on your thesis or research (not including the credits earned for the Outreachy internship)?', verbose_name='Number of graduate thesis or research credits'),
        ),
    ]
