# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20180106_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(help_text='What is one skill an the applicant needs to have in order to apply to your project, or what skill will they need to be willing to learn?', max_length=100, verbose_name='Skill description')),
                ('experience_level', models.CharField(choices=[('WTU', 'Mentors are willing to teach this skill to applicants with no experience at all'), ('CON', 'Applicants should have read about the skill'), ('EXP', 'Applicants should have used this skill in class or personal projects'), ('FAM', 'Applicants should be able to expand on their skills with the help of mentors'), ('CHA', 'Applicants who are experienced in this skill will have the chance to expand it further')], default='WTU', help_text='Choose this carefully! Many Outreachy applicants choose not to apply to a project unless they meet 100% of the project skill criteria.', max_length=3, verbose_name='Expected skill experience level')),
                ('requied', models.CharField(choices=[('BON', 'It would be nice if applicants had this skill, but it will not impact intern selection'), ('OPT', 'Mentors will prefer applicants who have this skill'), ('STR', 'Mentors will only accept applicants who have this skill as an intern')], default='BON', help_text='Is this skill a hard requirement, a preference, or an optional bonus? Choose this carefully! Many Outreachy applicants choose not to apply to a project unless they meet 100% of the project skill criteria.', max_length=3, verbose_name='Skill impact on intern selection')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Project', verbose_name='Project')),
            ],
        ),
    ]
