# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_projectskill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectskill',
            old_name='requied',
            new_name='required',
        ),
    ]
