# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 01:53
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20180201_0125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeCommitment',
            new_name='VolunteerTimeCommitment',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='time_commitments',
        ),
        migrations.AddField(
            model_name='applicantapproval',
            name='other_time_commitments',
            field=ckeditor.fields.RichTextField(blank=True, help_text='(Optional) If you have other time commitments outside of school, work, or volunteer hours, please use this field to let your mentor know. Examples of other time commitments include vacation that lasts longer than a week, coding school time commitments, community or online classes, etc.'),
        ),
        migrations.AddField(
            model_name='applicantapproval',
            name='volunteer_time_commitments',
            field=models.NullBooleanField(help_text='Will you have volunteer time commitments that require more than 10 hours a week during the Outreachy internship period?'),
        ),
    ]
