# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-22 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20180321_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internselection',
            name='intern_contract',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.SignedContract'),
        ),
    ]
