# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-22 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_auto_20180322_0118'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='internselection',
            unique_together=set([('applicant', 'project')]),
        ),
    ]
