# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_auto_20180109_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='community_benefits',
            field=models.CharField(blank=True, help_text='How will this project benefit the parent FOSS community?', max_length=800),
        ),
        migrations.AddField(
            model_name='project',
            name='intern_benefits',
            field=models.CharField(blank=True, help_text='What will the intern learn from working on this project?', max_length=800),
        ),
    ]
