# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-23 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_auto_20180322_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internselection',
            name='organizer_approved',
            field=models.NullBooleanField(default=None, help_text='Is this intern and funding information confirmed to be correct by the Outreachy organizers?'),
        ),
    ]
