# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_auto_20180201_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteertimecommitment',
            name='description',
            field=models.TextField(blank=True, help_text='Please describe what kind of volunteer position and duties you have.', max_length=3000),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='under_export_control',
            field=models.NullBooleanField(help_text='See the <a href="https://www.treasury.gov/resource-center/sanctions/Programs/Pages/Programs.aspx">US export control and sanctions list</a> for more information', verbose_name='Are you a person or entity restricted by United States of America export controls or sanctions programs?'),
        ),
        migrations.AlterField(
            model_name='volunteertimecommitment',
            name='end_date',
            field=models.DateField(help_text='Date your volunteer time commitments end. Use YYYY-MM-DD format.'),
        ),
        migrations.AlterField(
            model_name='volunteertimecommitment',
            name='hours_per_week',
            field=models.IntegerField(help_text='Maximum hours per week spent volunteering.'),
        ),
        migrations.AlterField(
            model_name='volunteertimecommitment',
            name='start_date',
            field=models.DateField(help_text='Date your volunteer time commitments start. Use YYYY-MM-DD format.'),
        ),
    ]
