# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_auto_20180109_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repository',
            field=models.URLField(blank=True, help_text="(Optional) Please provide a URL for your project's repository or contribution mechanism"),
        ),
    ]
