# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-23 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20180323_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signedcontract',
            name='text',
            field=models.TextField(max_length=100000, verbose_name='Contract text'),
        ),
    ]
