# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_project_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='issue_tracker',
            field=models.URLField(blank=True, help_text="(Optional) URL for your project's issue tracker"),
        ),
        migrations.AddField(
            model_name='project',
            name='newcomer_issue_tag',
            field=models.CharField(blank=True, help_text='(Optional) What tag is used for newcomer-friendly issues for your project?', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='repository',
            field=models.URLField(blank=True, help_text="(Optional) URL for your project's repository or contribution mechanism"),
        ),
    ]
