# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-02 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20180201_0358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name_plural': 'communities'},
        ),
        migrations.AlterModelOptions(
            name='newcommunity',
            options={'verbose_name_plural': 'new communities'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['slug']},
        ),
        migrations.AlterField(
            model_name='comrade',
            name='pronouns_public',
            field=models.BooleanField(default=False, help_text="Mentor, coordinator, and accepted interns' pronouns will be displayed publicly on the Outreachy website to anyone who is not logged in. Sharing pronouns can be a way for people to proudly display their gender identity and connect with other Outreachy participants, but other people may prefer to keep their pronouns private.<br>If this box is unchecked, Outreachy participants will be instructed to use they/them pronouns on public community channels. They will still know what your pronouns are if you check the previous box.", verbose_name='Share pronouns publicly'),
        ),
        migrations.AlterField(
            model_name='comrade',
            name='pronouns_to_participants',
            field=models.BooleanField(default=True, help_text="If this box is checked, applicant pronouns will be shared with coordinators, mentors and volunteers. If the box is checked, coordinator and mentor pronouns will be shared with applicants.<br>If the box is unchecked, no pronouns will be displayed.<br>If you don't want to share your pronouns, all Outreachy organizer email that Cc's another participant will use they/them/their pronouns for you.", verbose_name='Share pronouns with Outreachy participants'),
        ),
    ]
