# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-29 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_auto_20180323_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundpage',
            name='internapproval',
            field=models.DateField(default='2017-11-05', verbose_name='Date interns are approved by the Outreachy organizers'),
        ),
    ]
