# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-02 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_auto_20180202_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comrade',
            name='location',
            field=models.CharField(blank=True, help_text="(Optional) Location - city, state/province, and country.<br>This field is unused for mentors and coordinators. Applicant's location will be shared with their mentors. If selected as an intern, this location will be publicly displayed on the Outreachy website.<br>If you are concerned about keeping your location private, you can share less information, such as just the country, or a larger town nearby.", max_length=100),
        ),
        migrations.AlterField(
            model_name='comrade',
            name='nick',
            field=models.CharField(blank=True, help_text="(Optional) The username or 'nick' you typically use when communicating on professional channels. If you don't have one yet, leave this blank and update it later.<br>For mentors and coordinators, this will be displayed to applicants. Applicants' username/nick will be shared with their mentors and coordinators. Accepted interns' username/nick will be displayed on the Outreachy website.", max_length=100, verbose_name='Forum, chat, or IRC username'),
        ),
    ]
