# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-20 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_comrade_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internselection',
            name='intern_contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.SignedContract'),
        ),
    ]
