# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-02 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_auto_20180202_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text="A link to the publicly submitted contribution. The contribution can be work in progress. The URL could a link to a GitHub/GitLab issue or pull request, a link to the mailing list archives for a patch, a Gerrit pull request or issue, a contribution change log on a wiki, a review of graphical design work, a posted case study or user experience study, etc. If you're unsure what URL to put here, ask your mentor.", verbose_name='Contribution URL')),
                ('description', models.TextField(help_text='Description of this contribution for review by the Outreachy coordinators and organizers during intern selection. If you used advanced tools to create this contribution, mention them here.', max_length=3000)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ApplicantApproval')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Project')),
            ],
        ),
        migrations.AddField(
            model_name='applicantapproval',
            name='project_contributions',
            field=models.ManyToManyField(through='home.Contribution', to='home.Project'),
        ),
    ]
