# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 06:57
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_auto_20180109_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='communication_norms',
            field=ckeditor.fields.RichTextField(blank=True, help_text='(Optional) After following the project communication channel link, are there any special instructions? For example: "Join the #outreachy Zulip channel and make sure to introduce yourself.'),
        ),
    ]
