# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-05 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_auto_20180202_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='date_merged',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Date contribution was accepted or merged'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribution',
            name='date_started',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date contribution was started'),
            preserve_default=False,
        ),
    ]
