# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-13 22:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_auto_20180613_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumsurvey',
            name='survey_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='alumsurveytracker',
            name='survey_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
