# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_auto_20180109_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='communication_tool',
            field=models.CharField(blank=True, help_text='(Optional) Name of the communication tool your project uses. E.g. "IRC", "Zulip", or "Discourse"', max_length=100),
        ),
    ]
