# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-14 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_auto_20180613_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumsurvey',
            name='address1',
            field=models.CharField(blank=True, max_length=800, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='alumsurvey',
            name='address2',
            field=models.CharField(blank=True, max_length=800, verbose_name='Address Line 2/District/Neighborhood'),
        ),
        migrations.AddField(
            model_name='alumsurvey',
            name='city',
            field=models.CharField(blank=True, max_length=800, verbose_name='Town/City'),
        ),
        migrations.AddField(
            model_name='alumsurvey',
            name='country',
            field=models.CharField(blank=True, max_length=800, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='alumsurvey',
            name='postal_code',
            field=models.CharField(blank=True, max_length=800, verbose_name='Zip/Postal Code'),
        ),
        migrations.AddField(
            model_name='alumsurvey',
            name='region',
            field=models.CharField(blank=True, max_length=800, verbose_name='State/Province/Region/County/Territory/Prefecture/Republic'),
        ),
        migrations.AlterField(
            model_name='alumsurveytracker',
            name='survey_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
