# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-14 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_auto_20180614_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumsurvey',
            name='recommend_outreachy',
            field=models.CharField(choices=[('1', '1 - never'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5 - maybe'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10 - enthusiastically')], default='5', max_length=2, verbose_name='(Required) How likely would you be to recommend a friend apply to Outreachy?'),
        ),
    ]
