# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 07:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_auto_20180109_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='communication_url',
            field=models.CharField(blank=True, help_text='(Optional) URL for your project`s communication channel. For IRC, use irc://<host>[:port]/[channel]. Since many applicants have issues with IRC port blocking at their universities, IRC communication links will use <a href="https://kiwiirc.com/">Kiwi IRC</a> to embed the IRC communications in the project page.', max_length=200, validators=[django.core.validators.URLValidator(schemes=['http', 'https', 'irc'])]),
        ),
    ]
