# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_auto_20180109_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorapproval',
            name='instructions_read',
            field=models.BooleanField(default=False, help_text='I have read the <a href="/mentor/#mentor">mentor duties</a> and <a href="/mentor/mentor-faq/">mentor FAQ</a>.'),
        ),
    ]
