# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-06 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_auto_20180205_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField(help_text='Please describe your experience with this free software community and project as a user and as a contributor.', max_length=8000, verbose_name='Experience with this community')),
                ('foss_experience', models.TextField(help_text='Please describe your experience with any other free software projects as a user and as a contributor.', max_length=8000, verbose_name='Experience with other communities')),
                ('relevant_projects', models.TextField(help_text='Please describe any relevant projects (either personal, work, or school projects) that helped you gain skills you will use in this project. Talk about what knowledge you gained from working on them. Include links where possible.', max_length=8000, verbose_name='Relevant Projects')),
                ('timeline', models.TextField(help_text='Please work with your mentor to provide a timeline of the work you plan to accomplish on the project and what tasks you will finish at each step. Make sure take into account any time commitments you have during the Outreachy internship round.', max_length=8000, verbose_name='Outreachy internship project timeline')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ApplicantApproval')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Project')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='finalapplication',
            unique_together=set([('applicant', 'project')]),
        ),
    ]
