# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-06 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_auto_20180614_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='internselection',
            name='in_good_standing',
            field=models.BooleanField(default=True),
        ),
    ]
