# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-27 22:26
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_internselection_in_good_standing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.CharField(help_text='This should be three sentences for someone who has never heard of your community or the technologies involved. Do not put any links in the short description (use the long description instead).', max_length=800, verbose_name='Short description of community'),
        ),
        migrations.AlterField(
            model_name='community',
            name='long_description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Please avoid adding educational requirements for interns to your community description. Outreachy interns come from a variety of educational backgrounds. Schools around the world may not teach the same topics. If interns need to have specific skills, your mentors need to add application tasks to test those skills.', verbose_name='(Optional) Longer description of community.'),
        ),
        migrations.AlterField(
            model_name='community',
            name='tutorial',
            field=ckeditor.fields.RichTextField(blank=True, help_text='If your applicants need to complete a tutorial before working on contributions with mentors, please provide a description and the URL for the tutorial. For example, the Linux kernel asks applicants to complete a tutorial for compiling and installing a custom kernel, and sending in a simple whitespace change patch. Once applicants complete this tutorial, they can start to work with mentors on more complex contributions.', verbose_name='(Optional) Description of your first time contribution tutorial'),
        ),
        migrations.AlterField(
            model_name='community',
            name='website',
            field=models.URLField(blank=True, verbose_name="(Optional) Please provide the URL for your FOSS community's website"),
        ),
        migrations.AlterField(
            model_name='newcommunity',
            name='cla',
            field=models.URLField(blank=True, verbose_name="(Optional) Please provide the URL for your community's Contributor License Agreement (CLA)"),
        ),
        migrations.AlterField(
            model_name='newcommunity',
            name='code_of_conduct',
            field=models.URLField(blank=True, verbose_name="(Optional) Please provide the URL for to your community's Code of Conduct"),
        ),
        migrations.AlterField(
            model_name='newcommunity',
            name='community_size',
            field=models.CharField(choices=[('3', '1-2 people'), ('5', '3-5 people'), ('10', '6-10 people'), ('20', '11-20 people'), ('50', '21-50 people'), ('100', '50-100 people'), ('999', 'More than 100 people')], default='3', max_length=3, verbose_name='How many people are contributing to this FOSS community regularly?'),
        ),
        migrations.AlterField(
            model_name='newcommunity',
            name='dco',
            field=models.URLField(blank=True, verbose_name="(Optional) Please provide the URL for your community's Developer Certificate of Origin (DCO) agreement"),
        ),
        migrations.AlterField(
            model_name='newcommunity',
            name='goverance',
            field=models.URLField(blank=True, verbose_name="(Optional) Please provide the URL for a description of your community's governance model"),
        ),
        migrations.AlterField(
            model_name='newcommunity',
            name='longevity',
            field=models.CharField(choices=[('3M', '0-2 months'), ('6M', '3-5 months'), ('1Y', '6-11 months'), ('2Y', '1-2 years'), ('OL', 'More than 2 years')], default='3M', max_length=2, verbose_name='How long has this FOSS community accepted public contributions?'),
        ),
        migrations.AlterField(
            model_name='newcommunity',
            name='participating_orgs',
            field=models.CharField(help_text='If there are many organizations, list the top five organizations who make large contributions.', max_length=3000, verbose_name='What different organizations and companies participate in this FOSS community?'),
        ),
    ]
