# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-06 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_auto_20180206_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalapplication',
            name='timeline',
            field=models.TextField(blank=True, help_text='Please work with your mentor to provide a timeline of the work you plan to accomplish on the project and what tasks you will finish at each step. Make sure take into account any time commitments you have during the Outreachy internship round. If you are still working on your contributions and need more time, you can leave this blank and edit your application later.', max_length=8000, verbose_name='Outreachy internship project timeline'),
        ),
    ]
