# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_mentorapproval_instructions_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorapproval',
            name='longevity',
            field=models.CharField(choices=[('3M', '0-3 months'), ('6M', '3-6 months'), ('1Y', '6-12 months'), ('2Y', '1-2 years'), ('OL', 'More than 2 years')], default='3M', help_text='How long have you been contributing to this project?', max_length=2),
        ),
        migrations.AddField(
            model_name='mentorapproval',
            name='mentored_before',
            field=models.CharField(choices=[('OUT', 'Yes, for a past Outreachy round'), ('GSOC', 'Yes, for Google Summer of Code or Google Code In'), ('RAILS', 'Yes, for Rails Girls Summer of Code'), ('UNK', 'Yes, for another mentorship program'), ('NOT', 'No, I have never mentored before')], default='NOT', help_text='Have you been a mentor for a three-month internship program? (Note that Outreachy welcomes first time mentors, but this information allows the coordinator and other mentors to provide extra help to new mentors.)', max_length=4),
        ),
        migrations.AddField(
            model_name='mentorapproval',
            name='understands_applicant_time_commitment',
            field=models.BooleanField(default=False, help_text='I understand that Outreachy mentors often find they must spend more time helping applicants during the application period than helping their intern during the intership period'),
        ),
        migrations.AddField(
            model_name='mentorapproval',
            name='understands_intern_time_commitment',
            field=models.BooleanField(default=False, help_text='I understand that Outreachy mentors will spend a minimum of 5 hours a week mentoring their intern during the three month internship period'),
        ),
        migrations.AddField(
            model_name='mentorapproval',
            name='understands_mentor_contract',
            field=models.BooleanField(default=False, help_text='I understand that Outreachy mentors will need to sign a <a href="/documents/1/Outreachy-Program--Mentorship-Terms-of-Participation-May-2017.pdf">mentor contract</a> after they accept an applicant as an intern'),
        ),
    ]
