# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-08 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_auto_20180206_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comrade',
            name='pronouns',
            field=models.CharField(choices=[('she', 'she/her/hers'), ('he', 'he/him/his'), ('they', 'they/them/theirs'), ('fae', 'fae/faer/faers'), ('ey', 'ey/em/eirs'), ('per', 'per/per/pers'), ('ve', 've/ver/vis'), ('xe', 'xe/xem/xyrs'), ('ze', 'ze/hir/hirs')], default='they', help_text="Your preferred pronoun. This will be used in emails from Outreachy organizers directly to you. The format is subject/object/possessive pronoun. Example: '__(subject)__ interned with Outreachy. The mentor liked working with __(object)__. The opportunity was __(possessive pronoun)__ to grab.", max_length=4),
        ),
    ]
