# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-30 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_auto_20180727_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='amount',
            field=models.PositiveIntegerField(help_text='Sponsorship for each intern is $6,500.', verbose_name='Sponsorship amount'),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='funding_secured',
            field=models.BooleanField(default=False, help_text='\n            Check this box if funding has been confirmed by the sponsoring organization.\n            <br>Leave the box unchecked if the funding is tentative.\n            '),
        ),
        migrations.AlterField(
            model_name='sponsorship',
            name='name',
            field=models.CharField(help_text='The full sponsor name to be used on invoices.', max_length=100, verbose_name='Organization or company full legal name'),
        ),
    ]
