# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_auto_20180109_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorapproval',
            name='communication_channel_username',
            field=models.CharField(blank=True, help_text='What is your username on the project communication channel? (This information will be shared with applicants.)', max_length=100),
        ),
    ]
