# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-03 01:19
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_auto_20180730_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorapproval',
            name='communication_channel_username',
            field=models.CharField(blank=True, help_text='What is your username on the team communication channel? (This information will be shared with applicants.)', max_length=100, verbose_name='What is your username on the team communication channel?'),
        ),
        migrations.AlterField(
            model_name='mentorapproval',
            name='instructions_read',
            field=models.BooleanField(default=False, help_text='I have read the <a href="/mentor/#mentor">mentor duties</a> and <a href="/mentor/mentor-faq/">mentor FAQ</a>.', validators=[home.models.mentor_read_instructions], verbose_name='Understands mentor instructions'),
        ),
        migrations.AlterField(
            model_name='mentorapproval',
            name='longevity',
            field=models.CharField(choices=[('3M', '0-2 months'), ('6M', '3-5 months'), ('1Y', '6-11 months'), ('2Y', '1-2 years'), ('OL', 'More than 2 years')], default='3M', help_text='A community can be comprised of many different teams that each work on separate subsystems, modules, applications, libraries, tools, documentation, user experience, graphical design, and more. Typically each Outreachy project involves working with a particular team in the community. If the Outreachy intern would work with the whole community rather than a particular team, consider the community to be a team for these questions.<br><br>How long have you been a contributor on this team?', max_length=2, verbose_name='How long have you been a contributor on this team?'),
        ),
        migrations.AlterField(
            model_name='mentorapproval',
            name='mentor_foss_contributions',
            field=models.CharField(help_text='If none, what contributions have you made to other FOSS communities?', max_length=800, verbose_name='What contributions have you made to this team and this community?'),
        ),
        migrations.AlterField(
            model_name='mentorapproval',
            name='mentored_before',
            field=models.CharField(choices=[('OUT', 'Yes, I have mentored in a past Outreachy round'), ('GSOC', 'No, but I have mentored for Google Summer of Code or Google Code In'), ('RAILS', 'No, but I have mentored for Rails Girls Summer of Code'), ('UNK', 'No, but I have mentored with another mentorship program'), ('NOT', 'No, I have never mentored before')], default='NOT', help_text='Outreachy welcomes first time mentors, but this information allows the coordinator and other mentors to provide extra help to new mentors.', max_length=5, verbose_name='Have you been a mentor for Outreachy before?'),
        ),
        migrations.AlterField(
            model_name='mentorapproval',
            name='mentorship_style',
            field=models.CharField(help_text='Do you prefer short daily standups, longer weekly reports, or informal progress reports? Are you willing to try pair programming when your intern gets stuck? Do you like talking over video chat or answering questions via email? Give the applicants a sense of what it will be like to work with you during the internship.', max_length=800, verbose_name='What is your mentorship style?'),
        ),
        migrations.AlterField(
            model_name='mentorapproval',
            name='understands_applicant_time_commitment',
            field=models.BooleanField(default=False, help_text='I understand that Outreachy mentors often spend 5-10 hours a week helping applicants during the six week application period', validators=[home.models.mentor_read_instructions]),
        ),
        migrations.AlterField(
            model_name='mentorapproval',
            name='understands_intern_time_commitment',
            field=models.BooleanField(default=False, help_text='I understand that Outreachy mentors are required to spend a minimum of 5 hours a week mentoring their intern during the three month internship period', validators=[home.models.mentor_read_instructions]),
        ),
        migrations.AlterField(
            model_name='mentorapproval',
            name='understands_mentor_contract',
            field=models.BooleanField(default=False, help_text='I understand that Outreachy mentors will need to sign a <a href="https://github.com/sagesharp/outreachy-django-wagtail/blob/master/docs/mentor-agreement.md">mentor contract</a> after they accept an applicant as an intern', validators=[home.models.mentor_read_contract]),
        ),
        migrations.AlterField(
            model_name='project',
            name='community_size',
            field=models.CharField(choices=[('3', '1-2 people'), ('5', '3-5 people'), ('10', '6-10 people'), ('20', '11-20 people'), ('50', '21-50 people'), ('100', '50-100 people'), ('999', 'More than 100 people')], default='3', max_length=3, verbose_name='How many regular contributors does your team have?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contribution_tasks',
            field=ckeditor.fields.RichTextField(help_text='Instructions for how applicants can make contributions during the Outreachy application period.<br><br>Make sure to include links to getting started tutorials or documentation, how applicants can find contribution tasks on your project website or issue tracker, who they should ask for tasks, and everything they need to know to get started.', verbose_name='How can applicants make a contribution to your project?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.CharField(choices=[('NOW', 'Immediately close this project to new applicants'), ('REG', 'Open applications until the application period ends'), ('LAT', 'Extend applications through the late application deadline')], help_text="If you have too many applicants, and your most promising applicants have recorded both a contribution and a final application, you may want to close your project to new applicants.<br>If you have too few applicants, you may want to extend your project's application deadline by one week.", max_length=3, verbose_name='Project deadline'),
        ),
        migrations.AlterField(
            model_name='project',
            name='intern_tasks',
            field=ckeditor.fields.RichTextField(blank=True, help_text='(Optional) Description of possible internship tasks. What smaller tasks will they start on? What is the main task or tasks for the internship? Do you have any optional stretch goals?', max_length=3000),
        ),
        migrations.AlterField(
            model_name='project',
            name='long_description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Description of the internship project.<br><br>Please do not place educational restrictions (such as needing a degree) on this project. Outreachy applicants are judged on their demonstrated skills, not on their educational background. If your project requires knowledge that would normally be learned during a degree, your project contribution tasks should test applicants for that knowledge.<br><br>You should exclude applicant skills and communication channels. Those will be added in the next step.<br><br>You should also exclude discussion of internship tasks, internship benefits, repository URLs, issue tracker URLs, newcomer tags, or application period contribution tasks. Those are collected in the optional fields below.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='longevity',
            field=models.CharField(choices=[('3M', '0-2 months'), ('6M', '3-5 months'), ('1Y', '6-11 months'), ('2Y', '1-2 years'), ('OL', 'More than 2 years')], default='3M', help_text='A community can be comprised of many different teams that each work on separate subsystems, modules, applications, libraries, tools, documentation, user experience, graphical design, and more. Typically each Outreachy project involves working with a particular team in the community. If the Outreachy intern would work with the whole community rather than a particular team, consider the community to be a team for these questions.<br><br>How long has your team been accepting publicly submitted contributions?', max_length=2, verbose_name='How long has your team been accepting publicly submitted contributions?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='needs_more_applicants',
            field=models.BooleanField(default=False, help_text='Check this box to advertise this project as needing more applicants. This is typically used by projects without a lot of strong applicants two weeks before the application deadline.<br><br>You should uncheck this box if you already have many strong applicants who have filled out a final application.', verbose_name='Does your project need more applicants?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='newcomer_issue_tag',
            field=models.CharField(blank=True, help_text='(Optional) What tag is used for newcomer-friendly issues for your team or for this internship project? Please use a tag and not a URL.', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_title',
            field=models.CharField(help_text='Short title for this internship project proposal. This should be 100 characters or less, starting with a verb like "Create", "Improve", "Extend", "Survey", "Document", etc. Assume the applicant has never heard of your technology before and keep it simple. The short title will be used in your project page URL, so keep it short.', max_length=100, verbose_name='Project short title'),
        ),
    ]
