# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_mentorapproval_communication_channel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorapproval',
            name='mentored_before',
            field=models.CharField(choices=[('OUT', 'Yes, I have mentored in a past Outreachy round'), ('GSOC', 'No, but I have mentored for Google Summer of Code or Google Code In'), ('RAILS', 'No, but I have mentored for Rails Girls Summer of Code'), ('UNK', 'No, but I have mentored with another mentorship program'), ('NOT', 'No, I have never mentored before')], default='NOT', help_text='Have you been a mentor for Outreachy before? (Note that Outreachy welcomes first time mentors, but this information allows the coordinator and other mentors to provide extra help to new mentors.)', max_length=4),
        ),
    ]
