# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-03 02:12
from __future__ import unicode_literals

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_auto_20180803_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationchannel',
            name='communication_help',
            field=models.URLField(blank=True, help_text='(Optional) URL for the documentation for your communication tool. This should be user-focused documentation that explains the basic mechanisms of logging in and features. Suggestions: IRC - https://wiki.gnome.org/Outreachy/IRC; Zulip - https://chat.zulip.org/help/; Mattersmost - https://docs.mattermost.com/guides/user.html', verbose_name='Communication tool documentation URL'),
        ),
        migrations.AlterField(
            model_name='communicationchannel',
            name='instructions',
            field=ckeditor.fields.RichTextField(blank=True, help_text='(Optional) After following the communication channel link, are there any special instructions? For example: "Join the #outreachy channel and make sure to introduce yourself.', verbose_name='Instructions on joining'),
        ),
        migrations.AlterField(
            model_name='communicationchannel',
            name='norms',
            field=ckeditor.fields.RichTextField(blank=True, help_text="(Optional) What communication norms would a newcomer need to know about this communication channel? Example: newcomers to open source don't know they should Cc their mentor or the software maintainer when asking a question to a large mailing list. Think about what a newcomer would find surprising when communicating on this channel.", verbose_name='Community norms'),
        ),
        migrations.AlterField(
            model_name='communicationchannel',
            name='tool_name',
            field=models.CharField(help_text='The name of the communication tool your project uses. E.g. "a mailing list", "IRC", "Zulip", "Mattermost", or "Discourse"', max_length=100, verbose_name='Communication tool name'),
        ),
        migrations.AlterField(
            model_name='communicationchannel',
            name='url',
            field=models.CharField(help_text='URL for the communication channel applicants will use to reach mentors and ask questions about this internship project. IRC URLs should be in the form irc://&lt;host&gt;[:port]/[channel]. Since many applicants have issues with IRC port blocking at their universities, IRC communication links will use <a href="https://kiwiirc.com/">Kiwi IRC</a> to direct applicants to a web-based IRC client. If this is a mailing list, the URL should be the mailing list subscription page.', max_length=200, validators=[django.core.validators.URLValidator(schemes=['http', 'https', 'irc'])], verbose_name='Communication channel URL'),
        ),
    ]
