# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 04:08
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_auto_20180109_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='long_description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='(Optional) Longer description of community.'),
        ),
        migrations.AddField(
            model_name='community',
            name='website',
            field=models.URLField(blank=True, help_text="(Optional) Please provide the URL for your FOSS community's website"),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.CharField(help_text='Short description of community. This should be three sentences for someone who has never heard of your community or the technologies involved. Do not put any links in the short description (use the long description instead).', max_length=800),
        ),
        migrations.AlterField(
            model_name='community',
            name='slug',
            field=models.SlugField(help_text='Community URL slug: https://www.outreachy.org/communities/SLUG/', unique=True),
        ),
    ]
