# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-09 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_auto_20180209_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comrade',
            name='agreed_to_code_of_conduct',
            field=models.CharField(max_length=800, verbose_name='Type your legal name to indicate you agree to the Code of Conduct'),
        ),
    ]
