# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 06:05
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_auto_20180110_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contribution_tasks',
            field=ckeditor.fields.RichTextField(default='TBD', help_text='Instructions for how applicants can make contributions during the Outreachy application period. Make sure to include links to getting started tutorials or documentation, how applicants can find contribution tasks on your project website or issue tracker, who they should ask for tasks, and everything they need to know to get started.'),
            preserve_default=False,
        ),
    ]
