# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-10 15:25
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_auto_20180209_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='tutorial',
            field=ckeditor.fields.RichTextField(blank=True, help_text='(Optional) If your applicants need to complete a tutorial before working on their contributions, please provide a description and the URL for the tutorial'),
        ),
    ]
