# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-12 20:18
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_auto_20180808_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcommunity',
            name='approved_advertising',
            field=models.BooleanField(default=False, help_text='I assert that my community resources do not advertise the services of only one company. Community resources are where users and developers seek help for your FOSS project. Community resources can include the community website, mailing lists, forums, documentation, or community introduction emails. It is fine to advertise the services of multiple companies or to identify sponsor companies generally.'),
        ),
        migrations.AddField(
            model_name='newcommunity',
            name='unapproved_advertising_description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='(Optional) If your community resources advertise the services of only one community, please explain.'),
        ),
    ]
