# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-14 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_auto_20180812_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comrade',
            name='photo',
            field=models.ImageField(blank=True, help_text='File limit size is 1MB. For best display, use a square photo at least 200x200 pixels.', upload_to=home.models.make_comrade_photo_filename),
        ),
    ]
