# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-10 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_auto_20180210_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalapplication',
            name='approval_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('W', 'Withdrawn'), ('R', 'Rejected')], default='W', max_length=1),
        ),
        migrations.AddField(
            model_name='finalapplication',
            name='reason_denied',
            field=models.CharField(blank=True, help_text='\n            Please explain why you are withdrawing this request. This\n            explanation will only be shown to Outreachy organizers and\n            approved people within this community.\n            ', max_length=3000),
        ),
    ]
