# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-28 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_auto_20180814_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundpage',
            name='finalpayment',
            field=models.IntegerField(default=2500, null=True),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='initialfeedback',
            field=models.DateField(blank=True, default='2017-12-20', null=True, verbose_name='Date initial feedback is due'),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='initialpayment',
            field=models.IntegerField(default=1000, null=True),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='midpayment',
            field=models.IntegerField(default=2000, null=True),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='midfeedback',
            field=models.DateField(blank=True, default='2018-01-31', verbose_name='Date mid-point feedback is due'),
        ),
    ]
