# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-28 18:32
from __future__ import unicode_literals

from django.db import migrations
import datetime

def update_old_rounds(apps, schema_editor):
    # Get models
    RoundPage = apps.get_model('home.RoundPage')
    rounds = RoundPage.objects.all()
    for r in rounds:
        if r.internstarts < datetime.date(2018, 8, 28):
            r.initialfeedback = r.internstarts + datetime.timedelta(days=10)
            r.initialpayment = 500
            r.midpayment = 2250
            r.finalpayment = 2750
        else:
            r.initialfeedback = r.internstarts + datetime.timedelta(days=15)
            r.initialpayment = 1000
            r.midfeedback = r.internstarts + datetime.timedelta(days=57)
            r.midpayment = 2000
            r.finalpayment = 2500
        r.save()

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_auto_20180828_1831'),
    ]

    operations = [
        migrations.RunPython(update_old_rounds),
    ]
