# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-28 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_auto_20180828_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundpage',
            name='finalpayment',
            field=models.IntegerField(default=2500),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='initialfeedback',
            field=models.DateField(blank=True, default='2017-12-20', verbose_name='Date initial feedback is due'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='initialpayment',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='midpayment',
            field=models.IntegerField(default=2000),
        ),
    ]
