# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-01 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_auto_20180828_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCommitmentSummary',
            fields=[
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.ApplicantApproval')),
                ('enrolled_as_student', models.BooleanField(help_text='Will you be enrolled in a university or college during the Outreachy internship period? University and college students will be asked questions about the number of credits they are taking. Please state yes even if only a few days overlap with the internship period.', verbose_name='Are you or will you be a university or college student during the internship period?')),
                ('enrolled_as_noncollege_student', models.BooleanField(help_text='Will you be enrolled in a coding school or self-paced online classes during the Outreachy internship period? If you are taking classes without receiving credits, select this option.', verbose_name='Are you enrolled in a coding school or self-paced online courses?')),
                ('employed', models.BooleanField(help_text='Will you be an employee (for any number of hours) during the Outreachy internship period?')),
                ('contractor', models.BooleanField(help_text='Will you be a contractor during the Outreachy internship period?')),
                ('volunteer_time_commitments', models.BooleanField(help_text='Will you have any volunteer positions (such as volunteering with a non-profit or community center, participating in a community band, or volunteering to organize an event) that require more than 10 hours a week during the Outreachy internship period? Do not count your Outreachy internship time as a volunteer position.')),
                ('other_time_commitments', models.TextField(blank=True, help_text='(Optional) If you have other time commitments outside of school, work, or volunteer hours, please use this field to let your mentor know. Examples of other time commitments include vacation that lasts longer than a week, coding school time commitments, community or online classes, etc.', max_length=3000)),
            ],
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='employed',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='enrolled_as_noncollege_student',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='enrolled_as_student',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='other_time_commitments',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='volunteer_time_commitments',
        ),
    ]
