# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-01 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_auto_20180901_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecommitmentsummary',
            name='enrolled_as_student',
            field=models.BooleanField(help_text='Will you be enrolled in a university or college during the Outreachy internship period? University and college students will be asked questions about the number of credits they are taking. Please state yes even if only a few days overlap with the internship period.', verbose_name='Are you (or will you be) a university or college student during the internship period?'),
        ),
    ]
