# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-01 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_auto_20180901_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkEligibility',
            fields=[
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.ApplicantApproval')),
                ('over_18', models.BooleanField(verbose_name='Will you be 18 years or older when the Outreachy internship starts?')),
                ('eligible_to_work', models.BooleanField(help_text='<b>Student visas</b>: Please note that in some countries, students studying abroad on a student visa may not be eligible to work full-time (40 hours a week). If you are on a student visa, please double check with your school counselors before applying. <b>Spouse visas</b>: In some countries, spousal visas may not allow spouses to work. Please contact your immigration officer if you have any questions about whether your visa allows you to work full-time (40 hours a week).', verbose_name='Are you eligible to work for 40 hours a week in ALL the countries you will be living in for the entire internship period, and five weeks after the internship period ends?')),
                ('under_export_control', models.BooleanField(help_text='See the <a href="https://www.treasury.gov/resource-center/sanctions/Programs/Pages/Programs.aspx">US export control and sanctions list</a> for more information', verbose_name='Are you a person or entity restricted by United States of America export controls or sanctions programs?')),
                ('us_sanctioned_country', models.BooleanField(help_text="Outreachy's fiscal parent, Software Freedom Conservancy, is a 501(c)(3) U.S. non-profit. As a U.S. non-profit, Conservancy must ensure that funds are not sent to countries under U.S. sanctions programs, such as Cuba, Iran, North Korea, or Syria. If you have citizenship with Cuba, Iran, North Korea, or Syria, please answer yes, even if you are not currently living in those countries. We will follow up with additional questions.", verbose_name='Are you a citizen, resident, or national of Crimea, Cuba, Iran, North Korea, or Syria?')),
            ],
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='eligible_to_work',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='over_18',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='under_export_control',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='us_sanctioned_country',
        ),
    ]
