# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-03 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_auto_20180901_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEligibility',
            fields=[
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.ApplicantApproval')),
                ('us_national_or_permanent_resident', models.BooleanField(help_text='Outreachy is open to applicants around the world. This question is only to determine which tax form you will need to fill out.', verbose_name='Are you a national or permanent resident of the United States of America?')),
                ('living_in_us', models.BooleanField(help_text='Please answer yes even if you are a citizen of a country other than the USA.', verbose_name='Will you be living in the United States of America during the Outreachy internship period, or for up to five weeks after the internship period ends?')),
            ],
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='living_in_us',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='us_national_or_permanent_resident',
        ),
    ]
