# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-03 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_auto_20180903_0357'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicantapproval',
            unique_together=set([('applicant', 'application_round')]),
        ),
    ]
