# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-04 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_auto_20180903_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantGenderIdentity',
            fields=[
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.ApplicantApproval')),
                ('transgender', models.BooleanField(help_text='If you are questioning whether you are transgender, please say yes.', verbose_name='Do you identify as transgender?')),
                ('genderqueer', models.BooleanField(help_text='Do you identify as genderqueer, gender non-conforming, gender diverse, gender varient, or gender expansive? If you are questioning whether you identify with any of those terms, please say yes.', verbose_name='Do you identify as genderqueer?')),
                ('man', models.BooleanField()),
                ('woman', models.BooleanField()),
                ('demi_boy', models.BooleanField()),
                ('demi_girl', models.BooleanField()),
                ('non_binary', models.BooleanField()),
                ('demi_non_binary', models.BooleanField()),
                ('genderflux', models.BooleanField()),
                ('genderfluid', models.BooleanField()),
                ('demi_genderfluid', models.BooleanField()),
                ('demi_gender', models.BooleanField()),
                ('bi_gender', models.BooleanField()),
                ('tri_gender', models.BooleanField()),
                ('multigender', models.BooleanField()),
                ('pangender', models.BooleanField()),
                ('maxigender', models.BooleanField()),
                ('aporagender', models.BooleanField()),
                ('intergender', models.BooleanField()),
                ('mavrique', models.BooleanField()),
                ('gender_confusion', models.BooleanField()),
                ('gender_indifferent', models.BooleanField()),
                ('graygender', models.BooleanField()),
                ('agender', models.BooleanField()),
                ('genderless', models.BooleanField()),
                ('gender_neutral', models.BooleanField()),
                ('neutrois', models.BooleanField()),
                ('androgynous', models.BooleanField()),
                ('androgyne', models.BooleanField()),
                ('prefer_not_to_say', models.BooleanField()),
                ('self_identify', models.CharField(blank=True, help_text="If your gender identity is NOT listed above, what is your gender identity? Please note that 'gender identity' is NOT your name. Gender identity is your gender.", max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='agender',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='androgyne',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='androgynous',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='aporagender',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='bi_gender',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='demi_boy',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='demi_gender',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='demi_genderfluid',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='demi_girl',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='demi_non_binary',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='gender_confusion',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='gender_indifferent',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='gender_neutral',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='genderfluid',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='genderflux',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='genderless',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='genderqueer',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='graygender',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='intergender',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='man',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='mavrique',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='maxigender',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='multigender',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='neutrois',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='non_binary',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='pangender',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='prefer_not_to_say',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='self_identify',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='transgender',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='tri_gender',
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='woman',
        ),
    ]
