# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-04 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_auto_20180904_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantgenderidentity',
            name='trans_feminine',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicantgenderidentity',
            name='trans_masculine',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
