# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-04 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_auto_20180904_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantRaceEthnicityInformation',
            fields=[
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.ApplicantApproval')),
                ('us_resident_demographics', models.NullBooleanField(verbose_name='Are you Black/African American, Hispanic/Latin@, Native American, Alaska Native, Native Hawaiian, or Pacific Islander?')),
            ],
        ),
        migrations.RemoveField(
            model_name='applicantapproval',
            name='us_resident_demographics',
        ),
    ]
