# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-04 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_auto_20180904_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorFOSSExperience',
            fields=[
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.ApplicantApproval')),
                ('gsoc_or_outreachy_internship', models.BooleanField(help_text='Have you been accepted as a Google Summer of Code intern or an Outreachy intern before? Please say yes even if you did not successfully complete the internship.', verbose_name='Previous Google Summer of Code or Outreachy internship?')),
                ('prior_contributor', models.BooleanField(help_text='Please exclude contributions that were made as part of a prior Outreachy application period. Outreachy is open to people who have never contributed to free and open source software before.', verbose_name='Have you contributed to free and open source software before?')),
                ('prior_paid_contributor', models.BooleanField(help_text='Please include paid internships, contract work, employment, stipends, or grants.', verbose_name='Have you ever been <b>paid to contribute</b> to free and open source software before?')),
                ('prior_contrib_coding', models.BooleanField(verbose_name='Programming')),
                ('prior_contrib_forums', models.BooleanField(verbose_name='Participating in forums')),
                ('prior_contrib_events', models.BooleanField(verbose_name='Organizing events')),
                ('prior_contrib_issues', models.BooleanField(verbose_name='Reporting issues')),
                ('prior_contrib_devops', models.BooleanField(verbose_name='Running project infrastructure')),
                ('prior_contrib_docs', models.BooleanField(verbose_name='Documentation')),
                ('prior_contrib_data', models.BooleanField(verbose_name='Data science')),
                ('prior_contrib_translate', models.BooleanField(verbose_name='Translation')),
                ('prior_contrib_illustration', models.BooleanField(verbose_name='Graphical design')),
                ('prior_contrib_ux', models.BooleanField(verbose_name='User experience')),
                ('prior_contrib_short_talk', models.BooleanField(verbose_name='Giving a short talk')),
                ('prior_contrib_testing', models.BooleanField(verbose_name='Testing releases or quality assurance')),
                ('prior_contrib_security', models.BooleanField(verbose_name='Improving security or pen testing')),
                ('prior_contrib_marketing', models.BooleanField(verbose_name='Marketing for projects')),
                ('prior_contrib_reviewer', models.BooleanField(verbose_name='Reviewing contributions')),
                ('prior_contrib_mentor', models.BooleanField(verbose_name='Mentoring contributors')),
                ('prior_contrib_accessibility', models.BooleanField(verbose_name='Improving or testing accessibility')),
            ],
        ),
    ]
