# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-04 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0080_auto_20180904_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantraceethnicityinformation',
            name='us_resident_demographics',
            field=models.BooleanField(default=False, verbose_name='Are you Black/African American, Hispanic/Latin@, Native American, Alaska Native, Native Hawaiian, or Pacific Islander?'),
            preserve_default=False,
        ),
    ]
