# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-04 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0081_auto_20180904_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarriersToParticipation',
            fields=[
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.ApplicantApproval')),
                ('barriers_to_contribution', models.TextField(verbose_name='What barriers or concerns have kept you from contributing to free and open source software?')),
                ('systematic_bias', models.TextField(help_text='Contributing to free and open source software takes some skill. You may have already learned some basic skills through university or college classes, specialized schools, online classes, online resources, or with a mentor, friend, family member or co-worker. In these settings, have you faced systematic bias or discrimination? Have you been discouraged from accessing to these resources because of your identity or background?', verbose_name='What systematic bias or discrimination have you faced while building your skills for contributing to free and open source software?')),
            ],
        ),
    ]
