# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-08 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0082_barrierstoparticipation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantapproval',
            name='gsoc_or_outreachy_internship',
        ),
    ]
