# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-08 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0084_workeligibility_student_visa_restrictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workeligibility',
            name='student_visa_restrictions',
            field=models.BooleanField(help_text='Your student visa must allow you to work 40 hours a week for you to be eligible for Outreachy. If you are on a student visa in the United States of America, you might have limited dates when you can work 40 hours a week. We will work with you to shift your internship dates by up to five weeks. However, we cannot accommodate shortening the 12 week internship. Students on an F-1 visa might need to provide their university documentation to apply for CPT. Outreachy organizers can provide you CPT documentation once you are selected as an intern.', verbose_name='Do you have a student visa that limits the dates that you can work 40 hours a week during the internship period?'),
        ),
    ]
