# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-08 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0086_auto_20180908_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='priorfossexperience',
            name='prior_contrib_self_identify',
            field=models.CharField(blank=True, max_length=100, verbose_name='If your contribution type is NOT listed above, how have you contributed to free and open source software before?'),
        ),
    ]
