# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-12 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0088_auto_20180912_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantapproval',
            name='submission_date',
            field=models.DateField(auto_now_add=True, default='2018-01-01'),
            preserve_default=False,
        ),
    ]
