# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-13 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0089_applicantapproval_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantraceethnicityinformation',
            name='us_resident_demographics',
            field=models.BooleanField(verbose_name='Are you Black/African American, Hispanic/Latinx, Native American, Alaska Native, Native Hawaiian, or Pacific Islander?'),
        ),
    ]
