# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-14 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0090_auto_20180913_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantapproval',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
            preserve_default=False,
        ),
    ]
