# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-14 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0092_promotiontracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotiontracking',
            name='id',
        ),
        migrations.AlterField(
            model_name='promotiontracking',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.ApplicantApproval'),
        ),
    ]
