# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-19 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0093_auto_20180914_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrierstoparticipation',
            name='lacking_representation',
            field=models.TextField(default='Applicant was not asked this question.', help_text="<p>Contributing to free and open source software takes some skill. You may have already learned some basic skills through university or college classes, specialized schools, online classes, online resources, or with a mentor, friend, family member or co-worker.</p><p>Did you find these learning environments were lacking representation of people who who share your identity or background?</p><p>Outreachy Organizers strongly encourage you to write your personal stories. We want you to know that we won't judge your writing style, grammar or spelling.</p>", verbose_name='Did you find that your learning environments were lacking representation of people who who share your identity or background?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='barrierstoparticipation',
            name='systematic_bias',
            field=models.TextField(help_text="<p>Contributing to free and open source software takes some skill. You may have already learned some basic skills through university or college classes, specialized schools, online classes, online resources, or with a mentor, friend, family member or co-worker.</p><p>In these settings, have you faced systematic bias or discrimination? Have you been discouraged from accessing these resources because of your identity or background?</p><p>Please provide specific examples and (optionally) statistics.</p><p>Outreachy Organizers strongly encourage you to write your personal stories. We want you to know that we won't judge your writing style, grammar or spelling.</p>", verbose_name='What systematic bias or discrimination have you faced while building your skills for contributing to free and open source software?'),
        ),
    ]
