# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-22 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0098_auto_20180919_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationReviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('W', 'Withdrawn'), ('R', 'Rejected')], default='W', max_length=1)),
                ('reason_denied', models.CharField(blank=True, help_text='\n            Please explain why you are withdrawing this request. This\n            explanation will only be shown to Outreachy organizers and\n            approved people within this community.\n            ', max_length=3000)),
                ('comrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Comrade')),
                ('reviewing_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.RoundPage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InitialApplicationReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_rating', models.CharField(choices=[('+3', '+3 - Essay shows a *strongly* compelling argument for how the applicant *both* faces discrimination/bias and is from a group underrepresented in the technology industry of their country'), ('+2', '+2 - Essay shows a *strongly* compelling argument for how the applicant *either* faces discrimination/bias or they are from a group underrepresented in technology industry of their country'), ('+1', '+1 - Essay shows a *weak* argument for how the applicant either faces discrimination/bias or they are from a group underrepresented in technology industry of their country'), ('??', '?? - Essay questions were too short or unclear to make a decision'), ('0', 'Not rated'), ('-1', '-1 - Essay questions did not show either discrimination/bias or underrepresentation'), ('-2', '-2 - Essay questions were not understood'), ('-3', '-3 - Essay answers were spam or trolling')], default='0', max_length=2)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ApplicantApproval')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ApplicationReviewer')),
            ],
        ),
    ]
