# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-29 00:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0102_barrierstoparticipation_applicant_should_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooltimecommitment',
            name='registered_credits',
            field=models.IntegerField(help_text="What is the total number of credits you are enrolled for this term?<br>If you aren't registered yet, please provide an approximate number of credits?", validators=[django.core.validators.MinValueValidator(1)], verbose_name="Total number of credits you're registered for"),
        ),
    ]
