# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-29 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0103_auto_20180929_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinformation',
            name='current_academic_calendar',
            field=models.URLField(default='', verbose_name='Link to your official academic calendar for your *current school term'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolinformation',
            name='next_academic_calendar',
            field=models.URLField(default='', help_text="If the calendar for your next term is not released yet, link to last year's academic calendar for that term.", verbose_name='Link to your official academic calendar for your *next school term*'),
            preserve_default=False,
        ),
    ]
