# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-29 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0104_auto_20180929_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinformation',
            name='school_term_updates',
            field=models.CharField(blank=True, help_text='<p>If the school terms above are incorrect, or you have forgotten to include a term that overlaps with the Outreachy internship period, please update your terms.<p>For each school term, please provide:</p><ol><li>The term name</li><li>The start date of classes for ALL students in the school</li><li>The end date of exams for ALL students in the school</li><li>The total number of credits you will be enrolled for this term</li><li>The total number of credits a student typically enrolls for during this school term.</li><li>If you are a graduate student, the subset of those credits you will be using for graduate research or thesis credits.</li><li>If you will receive any school credits for your Outreachy internship, how many credits will you receive during that term?</li></ol><p>Please do not modify your dates to differ from the starting dates in your academic calendar. Outreachy organizers cannot accept statements that you will start your classes late.</p><p>Please provide a link to your school website which proves that students are eligible to register for less than a full course load. Some schools, especially those in India, do not allow students to register for a part-time course load.</p>', max_length=3000, verbose_name='Provide any updates about your school term information'),
        ),
        migrations.AlterField(
            model_name='schoolinformation',
            name='current_academic_calendar',
            field=models.URLField(verbose_name='Link to your official academic calendar for your *current* school term'),
        ),
        migrations.AlterField(
            model_name='schoolinformation',
            name='next_academic_calendar',
            field=models.URLField(help_text="If the calendar for your next term is not released yet, link to last year's academic calendar for that term.", verbose_name='Link to your official academic calendar for your *next* school term'),
        ),
    ]
