# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-01 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0107_schoolinformation_applicant_should_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinformation',
            name='current_academic_calendar',
            field=models.URLField(help_text='For some students, their academic calendar is not available online (or is only available to students). In this case, please upload a copy of the PDF or a picture of your official academic calendar to a file sharing site and add the link to the file here. Do not leave off your academic calendar or your initial application will not be processed promptly.', verbose_name='Link to your official academic calendar for your *current* school term'),
        ),
        migrations.AlterField(
            model_name='schoolinformation',
            name='next_academic_calendar',
            field=models.URLField(help_text="If the calendar for your next term is not released yet, link to last year's academic calendar for that term. For some students, their academic calendar is not available online (or is only available to students). In this case, please upload a copy of the PDF or a picture of your official academic calendar to a file sharing site and add the link to the file here. Do not leave off your academic calendar or your initial application will not be processed promptly.", verbose_name='Link to your official academic calendar for your *next* school term'),
        ),
    ]
