# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-05 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0109_auto_20181001_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialapplicationreview',
            name='comments',
            field=models.TextField(blank=True, help_text='Please provide any comments on the status of this initial application, or questions you have while reviewing it.', max_length=8000, verbose_name='Reviewer comments'),
        ),
    ]
