# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-17 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0111_applicantapproval_review_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundpage',
            name='lateprojects',
            field=models.DateField(blank=True, default='2017-10-16', verbose_name='Last date to add projects'),
        ),
    ]
