# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-22 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0113_officialschool_officialschoolterm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newcommunity',
            old_name='goverance',
            new_name='governance',
        ),
    ]
