# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-31 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0113_officialschool_officialschoolterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundpage',
            name='coordinator_funding_deadline',
            field=models.DateField(default='2017-11-03', verbose_name='Date coordinators must mark funding sources for interns by'),
        ),
    ]
