# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-05 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0115_roundpage_mentor_intern_selection_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundpage',
            name='week_two_chat_text_date',
            field=models.DateTimeField(default='2018-12-10 13:00Z', verbose_name='Date and time of outreachy week two chat (text only)'),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='week_two_chat_text_url',
            field=models.URLField(blank=True, verbose_name='URL of the real-time text chat'),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='week_two_chat_video_date',
            field=models.DateTimeField(default='2017-12-10 16:00Z', verbose_name='Date and time of outreachy week two chat (video only)'),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='week_two_chat_video_url',
            field=models.URLField(blank=True, verbose_name='URL of the video chat'),
        ),
    ]
