# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-05 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0116_auto_20181205_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundpage',
            name='week_two_chat_video_date',
            field=models.DateTimeField(default='2018-12-10 16:00Z', verbose_name='Date and time of outreachy week two chat (video only)'),
        ),
    ]
