# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-13 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0117_initialmentorfeedback_organizer_payment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='internselection',
            name='initial_feedback_due',
            field=models.DateField(blank=True, null=True, verbose_name='Date initial feedback form opens'),
        ),
        migrations.AddField(
            model_name='internselection',
            name='initial_feedback_opens',
            field=models.DateField(blank=True, null=True, verbose_name='Date initial feedback form opens'),
        ),
    ]
