# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-13 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0121_auto_20181213_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='internselection',
            name='intern_ends',
            field=models.DateField(blank=True, null=True, verbose_name='Date the internship ends'),
        ),
        migrations.AddField(
            model_name='internselection',
            name='intern_starts',
            field=models.DateField(blank=True, null=True, verbose_name='Date the internship starts'),
        ),
    ]
