# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-13 23:54
from __future__ import unicode_literals

from django.db import migrations

def update_intern_selections(apps, schema_editor):
    InternSelection = apps.get_model('home.InternSelection')
    interns = InternSelection.objects.all()
    for i in interns:
        i.intern_starts = i.project.project_round.participating_round.internstarts
        i.intern_ends = i.project.project_round.participating_round.internends
        i.save()

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0122_auto_20181213_2353'),
    ]

    operations = [
        migrations.RunPython(update_intern_selections, reverse_code=migrations.RunPython.noop),
    ]
