# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-14 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0117_auto_20181205_1148'),
        ('home', '0125_auto_20181214_1707'),
    ]

    operations = [
    ]
