# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-14 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0126_merge_20181214_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialmentorfeedback',
            name='extension_date',
            field=models.DateField(blank=True, help_text="If you want to extend the internship, please pick a date when you will be asked to update your intern's initial feedback and authorize payment. Internships can be extended for up to five weeks. We don't recommend extending an internship for more than 1 week at initial feedback.", null=True),
        ),
    ]
