# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-14 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0127_auto_20181214_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialmentorfeedback',
            name='active_in_public',
            field=models.BooleanField(verbose_name="Has your intern been active on public project channels, such as the community's chat, forums, issue tracker, mailing list, etc?"),
        ),
        migrations.AlterField(
            model_name='initialmentorfeedback',
            name='allow_edits',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='initialmentorfeedback',
            name='asking_questions',
            field=models.BooleanField(verbose_name='Has your intern been asking questions about their first tasks?'),
        ),
        migrations.AlterField(
            model_name='initialmentorfeedback',
            name='checkin_frequency',
            field=models.CharField(choices=[('', 'Not scheduled yet'), ('D', 'Once per day'), ('M', 'Multiple times per week'), ('W', 'Once per week'), ('B', 'Every other week')], default='', max_length=1, verbose_name="How often do you have a real-time chat, video conference, or phone conversation to check in with your intern's progress on tasks?"),
        ),
        migrations.AlterField(
            model_name='initialmentorfeedback',
            name='extension_date',
            field=models.DateField(blank=True, help_text="If you want to extend the internship, please pick a date when you will be asked to update your intern's initial feedback and authorize payment. Internships can be extended for up to five weeks. We don't recommend extending an internship for more than 1 week at initial feedback. Please leave this field blank if you are not asking for an extension.", null=True),
        ),
        migrations.AlterField(
            model_name='initialmentorfeedback',
            name='full_time_effort',
            field=models.BooleanField(verbose_name='Do you believe your Outreachy intern is putting in a full-time, 40 hours a week effort into the internship?'),
        ),
        migrations.AlterField(
            model_name='initialmentorfeedback',
            name='intern_response_time',
            field=models.CharField(choices=[('1H', '1 hour'), ('3H', '3 hours'), ('6H', '6 hours'), ('12H', '12 hours'), ('1D', '1 day'), ('2D', '2-3 days'), ('4D', '4-5 days'), ('6D', '6-7 days'), ('>7D', '> 7 days')], max_length=3, verbose_name='On average, how long does it take for <b>your intern</b> to respond to your questions or feedback?'),
        ),
        migrations.AlterField(
            model_name='initialmentorfeedback',
            name='last_contact',
            field=models.DateField(verbose_name='What was the last date you were in contact with your intern?'),
        ),
        migrations.AlterField(
            model_name='initialmentorfeedback',
            name='mentor_response_time',
            field=models.CharField(choices=[('1H', '1 hour'), ('3H', '3 hours'), ('6H', '6 hours'), ('12H', '12 hours'), ('1D', '1 day'), ('2D', '2-3 days'), ('4D', '4-5 days'), ('6D', '6-7 days'), ('>7D', '> 7 days')], max_length=3, verbose_name="On average, how long does it take for <b>you</b> to respond to your intern's questions or requests for feedback?"),
        ),
        migrations.AlterField(
            model_name='initialmentorfeedback',
            name='payment_approved',
            field=models.BooleanField(help_text='Please base your answer on whether your intern has put in a full-time, 40 hours a week effort. They should have established communication with you and other mentors, and have started learning how to tackle their first tasks. If you are going to ask for an internship extension, please say no to this question.', verbose_name='Should your Outreachy intern be paid the initial $1,000 payment?'),
        ),
        migrations.AlterField(
            model_name='initialmentorfeedback',
            name='progress_report',
            field=models.TextField(verbose_name="Please provide a paragraph describing your intern's progress on establishing communication with you, connecting to your FOSS community, and ramping up on their first tasks."),
        ),
        migrations.AlterField(
            model_name='initialmentorfeedback',
            name='provided_onboarding',
            field=models.BooleanField(verbose_name='Have you provided documentation or other resources to help onboard your intern?'),
        ),
        migrations.AlterField(
            model_name='initialmentorfeedback',
            name='request_extension',
            field=models.BooleanField(help_text='Sometimes interns do not put in a full-time effort. In this case, one of the options is to delay payment of their stipend and extend their internship a specific number of weeks. You will be asked to re-evaluate your intern after the extension is done.', verbose_name='Does your intern need an extension?'),
        ),
    ]
