# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-14 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0128_auto_20181214_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='date_merged',
            field=models.DateField(blank=True, help_text='If this contribution is still in progress, you can leave this field blank and edit it later.', null=True, verbose_name='Date contribution was accepted or merged'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='date_started',
            field=models.DateField(verbose_name='Date contribution was started'),
        ),
        migrations.AlterField(
            model_name='employmenttimecommitment',
            name='end_date',
            field=models.DateField(help_text='End date of employment period.'),
        ),
        migrations.AlterField(
            model_name='employmenttimecommitment',
            name='start_date',
            field=models.DateField(help_text='Start date of employment period.'),
        ),
        migrations.AlterField(
            model_name='noncollegeschooltimecommitment',
            name='end_date',
            field=models.DateField(help_text='Date your coding school or online course ends.'),
        ),
        migrations.AlterField(
            model_name='noncollegeschooltimecommitment',
            name='start_date',
            field=models.DateField(help_text='Date your coding school or online course starts.'),
        ),
        migrations.AlterField(
            model_name='officialschoolterm',
            name='end_date',
            field=models.DateField(help_text='This is the date the university advertises for the last possible date of any exam for any student in the semester.', verbose_name='Date all exams end.'),
        ),
        migrations.AlterField(
            model_name='officialschoolterm',
            name='start_date',
            field=models.DateField(help_text='What is the first possible day of classes for all students?<br>If students who are in different school years or different semester numbers start classes on different dates, use the first possible date that students in that year or semester start classes.<br>If you do not know when the term will start, use the start date of that term from last year.', verbose_name='Date classes start.'),
        ),
        migrations.AlterField(
            model_name='schooltimecommitment',
            name='end_date',
            field=models.DateField(help_text='This is the date your university advertises for the last possible date of any exam for any student in your semester. Use the last possible exam date, even if your personal exams end sooner.', verbose_name='Date all exams end.'),
        ),
        migrations.AlterField(
            model_name='schooltimecommitment',
            name='start_date',
            field=models.DateField(help_text='What is the first possible day of classes for all students?<br>If you started this term late (or will start this term late), use the date that classes start for all students, not the late registration date.<br>If students who are in different school years or different semester numbers start classes on different dates, use the first possible date that students in your year or semester start classes.<br>If you do not know when the term will start, use the start date of that term from last year.', verbose_name='Date classes start.'),
        ),
        migrations.AlterField(
            model_name='signedcontract',
            name='date_signed',
            field=models.DateField(verbose_name='Date contract was signed'),
        ),
        migrations.AlterField(
            model_name='volunteertimecommitment',
            name='end_date',
            field=models.DateField(help_text='Date your volunteer time commitments end.'),
        ),
        migrations.AlterField(
            model_name='volunteertimecommitment',
            name='start_date',
            field=models.DateField(help_text='Date your volunteer time commitments start.'),
        ),
    ]
