# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-15 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0129_auto_20181214_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialInternFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_edits', models.BooleanField()),
                ('in_contact', models.BooleanField(verbose_name='Have you been in contact with your mentor to discuss how to approach your first tasks?')),
                ('asking_questions', models.BooleanField(verbose_name='Have you been asking questions about your first tasks?')),
                ('active_in_public', models.BooleanField(verbose_name="Have you been active on public project channels, such as the community's chat, forums, issue tracker, mailing list, etc?")),
                ('provided_onboarding', models.BooleanField(verbose_name='Has your mentor provided documentation or other resources to help you learn more about your community and your first tasks?')),
                ('checkin_frequency', models.CharField(choices=[('', 'Not scheduled yet'), ('D', 'Once per day'), ('M', 'Multiple times per week'), ('W', 'Once per week'), ('B', 'Every other week')], default='', max_length=1, verbose_name='How often does your mentor have a real-time chat, video conference, or phone conversation to check in with your progress on tasks?')),
                ('last_contact', models.DateField(verbose_name='What was the last date you were in contact with your mentor?')),
                ('intern_response_time', models.CharField(choices=[('1H', '1 hour'), ('3H', '3 hours'), ('6H', '6 hours'), ('12H', '12 hours'), ('1D', '1 day'), ('2D', '2-3 days'), ('4D', '4-5 days'), ('6D', '6-7 days'), ('>7D', '> 7 days')], max_length=3, verbose_name="On average, how long does it take for <b>you</b> to respond to your mentor's questions or feedback?")),
                ('mentor_response_time', models.CharField(choices=[('1H', '1 hour'), ('3H', '3 hours'), ('6H', '6 hours'), ('12H', '12 hours'), ('1D', '1 day'), ('2D', '2-3 days'), ('4D', '4-5 days'), ('6D', '6-7 days'), ('>7D', '> 7 days')], max_length=3, verbose_name='On average, how long does it take for <b>your mentor</b> to respond to your questions or requests for feedback?')),
                ('mentor_support', models.TextField(verbose_name='Please provide a paragraph describing how your mentor has (or has not) been helping you. This information will only be seen by Outreachy mentors. We want you to be honest with us if you are having trouble with your mentor, so we can help you get a better internship experience.')),
                ('hours_worked', models.CharField(choices=[('10H', '10 hours'), ('20H', '20 hours'), ('30H', '30 hours'), ('40H', '40 hours'), ('50H', '50 hours'), ('60H', '60 hours')], help_text='Include time you spend researching questions, communicating with your mentor and the community, reading about the project and the community, working on skills you need in order to complete your tasks, and working on the tasks themselves. Please be honest about the number of hours you are putting in.', max_length=3, verbose_name='What is the average number of hours per week you spend on your Outreachy internship?')),
                ('progress_report', models.TextField(verbose_name='Please provide a paragraph describing your progress on establishing communication with your mentor, and ramping up on your first tasks. This information will only be seen by Outreachy mentors. If you are having any difficulties or facing any barriers, please let us know, so we can help you.')),
                ('intern_selection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.InternSelection')),
            ],
        ),
    ]
