# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-16 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0131_auto_20181216_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialinternfeedback',
            name='checkin_frequency',
            field=models.CharField(choices=[('0', 'Not scheduled yet'), ('D', 'Once per day'), ('M', 'Multiple times per week'), ('W', 'Once per week'), ('B', 'Every other week')], default='0', max_length=1, verbose_name='How often does your mentor have a real-time chat, video conference, or phone conversation to check in with your progress on tasks?'),
        ),
        migrations.AlterField(
            model_name='initialmentorfeedback',
            name='checkin_frequency',
            field=models.CharField(choices=[('0', 'Not scheduled yet'), ('D', 'Once per day'), ('M', 'Multiple times per week'), ('W', 'Once per week'), ('B', 'Every other week')], default='0', max_length=1, verbose_name="How often do you have a real-time chat, video conference, or phone conversation to check in with your intern's progress on tasks?"),
        ),
    ]
