# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-02 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0133_roundpage_week_three_stuck_chat_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundpage',
            name='week_five_audience_chat_url',
            field=models.URLField(blank=True, verbose_name='URL of the week five chat to explain your project to a newcomer'),
        ),
    ]
