# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-18 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0134_roundpage_week_five_audience_chat_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundpage',
            name='week_seven_timeline_chat_url',
            field=models.URLField(blank=True, verbose_name='URL of the week seven chat to talk about project timeline modifications'),
        ),
    ]
