# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-19 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0137_auto_20190119_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internselection',
            name='midpoint_feedback_due',
            field=models.DateField(blank=True, verbose_name='Date mid-point feedback form due'),
        ),
        migrations.AlterField(
            model_name='internselection',
            name='midpoint_feedback_opens',
            field=models.DateField(blank=True, verbose_name='Date mid-point feedback form opens (typically 7 days before the mid-point feedback deadline)'),
        ),
    ]
