# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-31 10:33
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0138_auto_20190119_1920_squashed_0142_auto_20190121_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='minimum_system_requirements',
            field=ckeditor.fields.RichTextField(default='<p>No system requirements provided.</p>', help_text='What are the minimum computer requirements to contribute to this project during the application period? Examples: Operating system, CPU, memory, and hard drive space. <br><br>Many Outreachy applicants have older laptops. Many of them are working with ten year old systems (e.g. 1.6 GHz dual core with 2 GB of RAM). Please evaluate whether your project could better support contributors with older systems.'),
        ),
    ]
