# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-06 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0139_squashed_eligibility_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialschoolterm',
            name='typical_credits',
        ),
        migrations.RemoveField(
            model_name='schooltimecommitment',
            name='outreachy_credits',
        ),
        migrations.RemoveField(
            model_name='schooltimecommitment',
            name='registered_credits',
        ),
        migrations.RemoveField(
            model_name='schooltimecommitment',
            name='thesis_credits',
        ),
        migrations.RemoveField(
            model_name='schooltimecommitment',
            name='typical_credits',
        ),
        migrations.AlterField(
            model_name='schoolinformation',
            name='school_term_updates',
            field=models.TextField(blank=True, help_text='<p>If the school terms above are incorrect, or you have forgotten to include a term that overlaps with the Outreachy internship period, please update your terms.<p>For each school term, please provide:</p><ol><li>The term name</li><li>The start date of classes for ALL students in the school</li><li>The end date of exams for ALL students in the school</li></ol><p>Please do not modify your dates to differ from the starting dates in your academic calendar. Outreachy organizers cannot accept statements that you will start your classes late.</p>', max_length=3000, verbose_name='Provide any updates about your school term information'),
        ),
        migrations.AlterField(
            model_name='timecommitmentsummary',
            name='enrolled_as_noncollege_student',
            field=models.BooleanField(help_text='Will you be enrolled in a coding school or self-paced online classes during the Outreachy internship period?', verbose_name='Are you enrolled in a coding school or self-paced online courses?'),
        ),
        migrations.AlterField(
            model_name='timecommitmentsummary',
            name='enrolled_as_student',
            field=models.BooleanField(help_text='Will you be enrolled in a university or college during the Outreachy internship period? Please state yes even if only a few days overlap with the internship period.', verbose_name='Are you (or will you be) a university or college student during the internship period?'),
        ),
    ]
