# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-14 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0141_auto_20190206_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltimecommitment',
            name='last_term',
            field=models.BooleanField(default=False, help_text='This is the last term in my degree.'),
        ),
        migrations.AlterField(
            model_name='schoolinformation',
            name='current_academic_calendar',
            field=models.URLField(help_text="Please provide a link on your school's official website. Some schools do not make their calendars publicly available. You can upload your calendar to a file sharing service, but the Outreachy organizers may not take it into account when validating your school dates.", verbose_name='Link to your official academic calendar for your *current* school term'),
        ),
        migrations.AlterField(
            model_name='schoolinformation',
            name='next_academic_calendar',
            field=models.URLField(help_text="If the calendar for your next term is not released yet, link to last year's academic calendar for that term. Some schools do not make their calendars publicly available. You can upload your calendar to a file sharing service, but the Outreachy organizers may not take it into account when validating your school dates.", verbose_name='Link to your official academic calendar for your *next* school term'),
        ),
        migrations.AlterField(
            model_name='schooltimecommitment',
            name='end_date',
            field=models.DateField(help_text="This is the date your university advertises for the last possible date of any exam for any student in your semester. Use the last possible exam date, even if your personal exams end sooner. If you don't see a calendar pop-up, please use the date format YYYY-MM-DD.", verbose_name='Date all exams end.'),
        ),
        migrations.AlterField(
            model_name='schooltimecommitment',
            name='start_date',
            field=models.DateField(help_text="What is the first possible day of classes for all students?<br>If you started this term late (or will start this term late), use the date that classes start for all students, not the late registration date.<br>If students who are in different school years or different semester numbers start classes on different dates, use the first possible date that students in your year or semester start classes.<br>If you do not know when the term will start, use the start date of that term from last year.<br>If you don't see a calendar pop-up, please use the date format YYYY-MM-DD.", verbose_name='Date classes start.'),
        ),
    ]
