# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-21 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0141_auto_20190121_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midpointinternfeedback',
            name='intern_contribution_revision_time',
            field=models.CharField(choices=[('1H', '1 hour'), ('3H', '3 hours'), ('6H', '6 hours'), ('12H', '12 hours'), ('1D', '1 day'), ('2D', '2-3 days'), ('4D', '4-5 days'), ('6D', '6-7 days'), ('>7D', '> 7 days')], default='>7D', max_length=3, verbose_name="How long does it take for <b>you</b> to incorporate your mentor's feedback and resubmit a contribution?"),
        ),
        migrations.AlterField(
            model_name='midpointinternfeedback',
            name='mentor_help_response_time',
            field=models.CharField(choices=[('1H', '1 hour'), ('3H', '3 hours'), ('6H', '6 hours'), ('12H', '12 hours'), ('1D', '1 day'), ('2D', '2-3 days'), ('4D', '4-5 days'), ('6D', '6-7 days'), ('>7D', '> 7 days')], default='>7D', max_length=3, verbose_name='How long does it take for <b>your mentor</b> to respond to your requests for help?'),
        ),
        migrations.AlterField(
            model_name='midpointmentorfeedback',
            name='intern_contribution_revision_time',
            field=models.CharField(choices=[('1H', '1 hour'), ('3H', '3 hours'), ('6H', '6 hours'), ('12H', '12 hours'), ('1D', '1 day'), ('2D', '2-3 days'), ('4D', '4-5 days'), ('6D', '6-7 days'), ('>7D', '> 7 days')], default='>7D', max_length=3, verbose_name='How long does it take for <b>your intern</b> to incorporate feedback and resubmit a contribution?'),
        ),
        migrations.AlterField(
            model_name='midpointmentorfeedback',
            name='mentor_help_response_time',
            field=models.CharField(choices=[('1H', '1 hour'), ('3H', '3 hours'), ('6H', '6 hours'), ('12H', '12 hours'), ('1D', '1 day'), ('2D', '2-3 days'), ('4D', '4-5 days'), ('6D', '6-7 days'), ('>7D', '> 7 days')], default='>7D', max_length=3, verbose_name="How long does it take for <b>you</b> to respond to your intern's request for help?"),
        ),
    ]
