# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-15 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0142_auto_20190214_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenttimecommitment',
            name='job_title',
            field=models.CharField(max_length=100),
        ),
    ]
