# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-15 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0139_project_minimum_system_requirements'),
        ('home', '0143_auto_20190215_0155'),
    ]

    operations = [
    ]
