# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-18 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0144_merge_20190215_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='noncollegeschooltimecommitment',
            name='quit_on_acceptance',
            field=models.BooleanField(default=False, help_text='I will quit this coding school or stop this self-paced online course if I am accepted as an Outreachy intern.'),
            preserve_default=False,
        ),
    ]
