# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-22 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0146_auto_20190222_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='internselection',
            name='final_feedback_due',
            field=models.DateField(blank=True, null=True, verbose_name='Date mid-point feedback form due'),
        ),
        migrations.AddField(
            model_name='internselection',
            name='final_feedback_opens',
            field=models.DateField(blank=True, null=True, verbose_name='Date mid-point feedback form opens (typically 7 days before the mid-point feedback deadline)'),
        ),
    ]
