# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-22 17:18
from __future__ import unicode_literals

from django.db import migrations
import datetime

def update_intern_selections(apps, schema_editor):
    InternSelection = apps.get_model('home.InternSelection')
    interns = InternSelection.objects.all()
    # We need to send Conservancy the feedback on interns by Monday, March 11.
    # That means they're due on Thursday, March 7,
    # in order to give us time to ping mentors who haven't provided feedback.
    for i in interns:
        i.final_feedback_due = i.intern_ends + datetime.timedelta(days=3)
        i.final_feedback_opens = i.final_feedback_due - datetime.timedelta(days=7)
        i.save()

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0147_auto_20190222_1717'),
    ]

    operations = [
        migrations.RunPython(update_intern_selections, reverse_code=migrations.RunPython.noop),
    ]
