# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0150_finalinternfeedback_finalmentorfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalinternfeedback',
            name='chat_frequency',
            field=models.CharField(choices=[('1', 'Once a week'), ('2', 'Every 2 weeks'), ('3', 'Every 3 weeks'), ('4', 'Every 4 weeks'), ('6', 'Every 6 weeks'), ('12', 'Once during the internship'), ('NOP', 'No opinion')], default='NOP', max_length=3, verbose_name='How often do you feel Outreachy organizers should host a video chat for all interns during their 12 week internship?'),
        ),
        migrations.AddField(
            model_name='finalinternfeedback',
            name='recommend_intern_chat',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('DUN', "I don't know"), ('NOP', 'No opinion')], default='NOP', max_length=3, verbose_name='Should Outreachy organizers have video chats with all interns next round?'),
        ),
        migrations.AlterField(
            model_name='finalinternfeedback',
            name='blog_frequency',
            field=models.CharField(choices=[('1', 'Once a week'), ('2', 'Every 2 weeks'), ('3', 'Every 3 weeks'), ('4', 'Every 4 weeks'), ('6', 'Every 6 weeks'), ('12', 'Once during the internship'), ('NOP', 'No opinion')], default='NOP', max_length=3, verbose_name='How often do you feel Outreachy interns should blog during their 12 week internship?'),
        ),
    ]
