# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0114_auto_20181022_0725'),
        ('home', '0151_auto_20190226_2022'),
    ]

    operations = [
    ]
