# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0152_merge_20190401_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundpage',
            name='week_two_chat_video_date',
        ),
        migrations.RemoveField(
            model_name='roundpage',
            name='week_two_chat_video_url',
        ),
    ]
