# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0153_auto_20190430_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalapplication',
            name='experience',
            field=models.TextField(help_text='Please describe your experience before this Outreachy application period with this free software community. You can describe your prior experiences as both a user and a contributor.', max_length=8000, verbose_name='Past experience with this community'),
        ),
        migrations.AlterField(
            model_name='finalapplication',
            name='foss_experience',
            field=models.TextField(help_text='Please describe your experience before this Outreachy application period with any other free software communities. You can describe your prior experiences as both a user and a contributor.', max_length=8000, verbose_name='Past experience with other communities'),
        ),
    ]
