# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0154_auto_20190506_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roundpage',
            old_name='week_seven_timeline_chat_url',
            new_name='week_eight_timeline_chat_url',
        ),
        migrations.RenameField(
            model_name='roundpage',
            old_name='week_three_stuck_chat_url',
            new_name='week_four_stuck_chat_url',
        ),
        migrations.RenameField(
            model_name='roundpage',
            old_name='week_five_audience_chat_url',
            new_name='week_six_audience_chat_url',
        ),
        migrations.AddField(
            model_name='roundpage',
            name='week_eight_chat_text_date',
            field=models.DateTimeField(default='2018-12-10 13:00Z', verbose_name='Date and time of Outreachy week eight chat to talk about difficulties scoping project tasks'),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='week_four_chat_text_date',
            field=models.DateTimeField(default='2018-12-10 13:00Z', verbose_name="Date and time of Outreachy week four chat about what we're stuck on"),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='week_six_chat_text_date',
            field=models.DateTimeField(default='2018-12-10 13:00Z', verbose_name='Date and time of Outreachy week six chat to explain why your project passion to a newcomer'),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='week_ten_career_chat_url',
            field=models.URLField(blank=True, verbose_name='URL of the week ten chat to talk about career opportunities'),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='week_ten_chat_text_date',
            field=models.DateTimeField(default='2018-12-10 13:00Z', verbose_name='Date and time of Outreachy week ten chat to talk about career opportunities'),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='week_twelve_chat_text_date',
            field=models.DateTimeField(default='2018-12-10 13:00Z', verbose_name='Date and time of Outreachy week twelve chat to wrap up the Outreachy internship'),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='week_twelve_wrapup_chat_url',
            field=models.URLField(blank=True, verbose_name='URL of the week twelve chat to wrap up the Outreachy internship'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='week_eight_timeline_chat_url',
            field=models.URLField(blank=True, verbose_name='URL of the week eight chat to talk about project timeline modifications'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='week_four_stuck_chat_url',
            field=models.URLField(blank=True, verbose_name="URL of the week four chat on what we're stuck on"),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='week_six_audience_chat_url',
            field=models.URLField(blank=True, verbose_name='URL of the week six chat to explain your project to a newcomer'),
        ),
    ]
