# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 23:05
from __future__ import unicode_literals

from django.db import migrations, models


def update_projects(apps, schema_editor):
    Project = apps.get_model('home.Project')
    Project.objects.all().update(
        new_contributors_welcome=models.Case(
            models.When(deadline="NOW", then=models.Value(False)),
            default=models.Value(True),
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0156_project_new_contributors_welcome'),
    ]

    operations = [
        migrations.RunPython(update_projects, reverse_code=migrations.RunPython.noop),
    ]
