# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-14 20:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0158_auto_20190607_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundpage',
            name='appsclose',
        ),
        migrations.AddField(
            model_name='roundpage',
            name='contributions_close',
            field=models.DateField(default=datetime.date(1980, 1, 1), verbose_name='Date contributions close'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roundpage',
            name='contributions_open',
            field=models.DateField(default=datetime.date(1980, 1, 1), verbose_name='Date contributions open'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roundpage',
            name='initial_applications_close',
            field=models.DateField(default=datetime.date(1980, 1, 1), verbose_name='Date initial applications close'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roundpage',
            name='initial_applications_open',
            field=models.DateField(default=datetime.date(1980, 1, 1), verbose_name='Date initial applications open'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='appslate',
            field=models.DateField(verbose_name='Date extended applications are due'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='appsopen',
            field=models.DateField(verbose_name='Date applications open'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='coordinator_funding_deadline',
            field=models.DateField(verbose_name='Date coordinators must mark funding sources for interns by'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='finalfeedback',
            field=models.DateField(verbose_name='Date final feedback is due'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='initialfeedback',
            field=models.DateField(verbose_name='Date initial feedback is due'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='internannounce',
            field=models.DateField(verbose_name='Date interns are announced'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='internapproval',
            field=models.DateField(verbose_name='Date interns are approved by the Outreachy organizers'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='internends',
            field=models.DateField(verbose_name='Date internships end'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='internstarts',
            field=models.DateField(verbose_name='Date internships start'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='landingdue',
            field=models.DateField(verbose_name='Date community landing pages are due'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='lateorgs',
            field=models.DateField(verbose_name='Last date to add community landing pages'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='lateprojects',
            field=models.DateField(verbose_name='Last date to add projects'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='mentor_intern_selection_deadline',
            field=models.DateField(verbose_name='Date mentors must select their intern by'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='midfeedback',
            field=models.DateField(verbose_name='Date mid-point feedback is due'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='orgreminder',
            field=models.DateField(verbose_name='Date to remind orgs to submit their home pages'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='pingnew',
            field=models.DateField(verbose_name='Date to start pinging new orgs'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='pingold',
            field=models.DateField(verbose_name='Date to start pinging past orgs'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='week_eight_chat_text_date',
            field=models.DateTimeField(verbose_name='Date and time of Outreachy week eight chat to talk about difficulties scoping project tasks'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='week_four_chat_text_date',
            field=models.DateTimeField(verbose_name="Date and time of Outreachy week four chat about what we're stuck on"),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='week_six_chat_text_date',
            field=models.DateTimeField(verbose_name='Date and time of Outreachy week six chat to explain why your project passion to a newcomer'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='week_ten_chat_text_date',
            field=models.DateTimeField(verbose_name='Date and time of Outreachy week ten chat to talk about career opportunities'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='week_twelve_chat_text_date',
            field=models.DateTimeField(verbose_name='Date and time of Outreachy week twelve chat to wrap up the Outreachy internship'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='week_two_chat_text_date',
            field=models.DateTimeField(verbose_name='Date and time of outreachy week two chat (text only)'),
        ),
    ]
