# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-14 20:09
from __future__ import unicode_literals

from django.db import migrations, models


def copy_apps_contributions_dates(apps, schema_editor):
    RoundPage = apps.get_model('home.RoundPage')
    RoundPage.objects.all().update(
        initial_applications_open=models.F('appsopen'),
        initial_applications_close=models.F('appslate'),
        contributions_open=models.F('appsopen'),
        contributions_close=models.F('appslate'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0159_roundpage_split_apps_contributions'),
    ]

    operations = [
        migrations.RunPython(copy_apps_contributions_dates, reverse_code=migrations.RunPython.noop),
    ]
