# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-25 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0161_auto_20190704_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='project',
            name='needs_more_applicants',
        ),
        migrations.RemoveField(
            model_name='roundpage',
            name='appslate',
        ),
        migrations.RemoveField(
            model_name='roundpage',
            name='appsopen',
        ),
        migrations.AddField(
            model_name='roundpage',
            name='outreachy_chat',
            field=models.DateTimeField(null=True, verbose_name='Date and time of the Outreachy Twitter chat'),
        ),
    ]
