# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-31 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0164_auto_20190725_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roundpage',
            old_name='week_twelve_wrapup_chat_url',
            new_name='week_fourteen_wrapup_chat_url',
        ),
        migrations.AddField(
            model_name='roundpage',
            name='resume_reviewer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email address of the person doing resume review during week 12'),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='resume_reviewer_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name of the person doing resume review during week 12'),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='week_fourteen_chat_text_date',
            field=models.DateTimeField(null=True, verbose_name='Date and time of Outreachy week twelve chat to wrap up the Outreachy internship'),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='week_twelve_interviewing_chat_url',
            field=models.URLField(blank=True, verbose_name='URL of the week twelve chat on interviewing'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='week_twelve_chat_text_date',
            field=models.DateTimeField(verbose_name='Date and time of Outreachy week twelve chat on interviewing'),
        ),
    ]
