# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-31 19:15
from __future__ import unicode_literals
import datetime

from django.db import migrations

def update_rounds(apps, schema_editor):
    RoundPage = apps.get_model('home.RoundPage')
    rounds = RoundPage.objects.all()
    for r in rounds:
        r.week_twelve_chat_text_date = r.week_ten_chat_text_date + datetime.timedelta(days=14)
        r.week_fourteen_chat_text_date = r.week_ten_chat_text_date + datetime.timedelta(days=14*2)
        r.save()

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0165_auto_20190731_1915'),
    ]

    operations = [
        migrations.RunPython(update_rounds, reverse_code=migrations.RunPython.noop),
    ]
