# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-31 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0166_auto_20190731_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundpage',
            name='week_fourteen_chat_text_date',
            field=models.DateTimeField(verbose_name='Date and time of Outreachy week twelve chat to wrap up the Outreachy internship'),
        ),
    ]
