# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-13 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0167_auto_20190731_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundpage',
            name='week_fourteen_chat_text_date',
            field=models.DateTimeField(verbose_name='Date and time of Outreachy week fourteen chat to wrap up the Outreachy internship'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='week_fourteen_wrapup_chat_url',
            field=models.URLField(blank=True, verbose_name='URL of the week fourteen chat to wrap up the Outreachy internship'),
        ),
    ]
