# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-24 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0169_auto_20190813_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundpage',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Coupon code for the book "Forge Your Future with Open Source"'),
        ),
    ]
