# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-01 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0170_roundpage_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundpage',
            name='pick_a_project_blog_url',
            field=models.URLField(blank=True, verbose_name='URL of the blog on how to pick a project'),
        ),
    ]
