# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-25 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0173_auto_20191125_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundpage',
            name='final_payment_date',
            field=models.DateField(verbose_name='Date final payment will be received by'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='initial_payment_date',
            field=models.DateField(verbose_name='Date initial payment will be received by'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='midpoint_payment_date',
            field=models.DateField(verbose_name='Date mid-point payment will be received by'),
        ),
        migrations.AlterField(
            model_name='roundpage',
            name='tax_form_deadline',
            field=models.DateField(verbose_name='Date tax forms must be received by in order to have on-time initial payments'),
        ),
    ]
