# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-30 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0177_auto_20200522_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformalChatContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(verbose_name='Are you currently available for informal chats?')),
                ('name', models.CharField(blank=True, help_text='Your full name, which will be publicly displayed to Outreachy interns. This is typically your given name, followed by your family name. You may use a pseudonym or abbreviate your given or family names if you have concerns about privacy.', max_length=800)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email address')),
                ('relationship_to_outreachy', models.CharField(blank=True, help_text='Which are you: a current/past Outreachy intern, current/past Outreachy mentor, current/past Outreachy coordinator, or current employee of an Outreachy sponsor?', max_length=800)),
                ('foss_communities', models.CharField(blank=True, max_length=800, verbose_name='What open source communities do you participate in?')),
                ('company', models.CharField(blank=True, max_length=800, verbose_name='What company do you work for?')),
                ('paid_foss_roles', models.CharField(blank=True, max_length=800, verbose_name='What open source roles (e.g. community manager, JavaScript programmer, Linux systems admin) are you paid to work on?')),
                ('volunteer_foss_roles', models.CharField(blank=True, max_length=800, verbose_name='What open source roles (e.g. community manager, JavaScript programmer, Linux systems admin) do you volunteer for?')),
                ('comrade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Comrade')),
            ],
        ),
    ]
