# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-31 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0178_informalchatcontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comrade',
            name='nick_name',
        ),
    ]
