# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-07 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0181_mentorapproval_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectskill',
            name='experience_level',
            field=models.CharField(choices=[('WTU', 'No knowledge required'), ('CON', 'Concepts'), ('EXP', 'Experimented'), ('FAM', 'Comfortable'), ('CHA', 'Challenge')], default='WTU', help_text='Choose this carefully! Many Outreachy applicants choose not to apply for an internship project unless they meet 100% of the project skill criteria.', max_length=3, verbose_name='Expected skill experience level'),
        ),
        migrations.AlterField(
            model_name='projectskill',
            name='required',
            field=models.CharField(choices=[('BON', 'Optional'), ('OPT', 'Preferred'), ('STR', 'Required')], default='BON', max_length=3, verbose_name='Skill impact on intern selection'),
        ),
    ]
