# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-16 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0183_auto_20200808_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrierstoparticipation',
            name='employment_bias',
            field=models.TextField(verbose_name='What systemic bias or discrimination would you face if you applied for a job in the technology industry of your country?'),
        ),
        migrations.AlterField(
            model_name='barrierstoparticipation',
            name='lacking_representation',
            field=models.TextField(verbose_name='Does your learning environment have few people who share your identity or background? Please provide details.'),
        ),
        migrations.AlterField(
            model_name='barrierstoparticipation',
            name='systemic_bias',
            field=models.TextField(verbose_name='What systemic bias or discrimination have you faced while building your skills?'),
        ),
    ]
