# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-17 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0183_auto_20200808_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumsurvey',
            name='survey_tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.AlumSurveyTracker'),
        ),
        migrations.AlterField(
            model_name='applicantapproval',
            name='review_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.ApplicationReviewer'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Project'),
        ),
        migrations.AlterField(
            model_name='finalapplication',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Project'),
        ),
        migrations.AlterField(
            model_name='informalchatcontact',
            name='comrade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Comrade'),
        ),
        migrations.AlterField(
            model_name='internselection',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Project'),
        ),
        migrations.AlterField(
            model_name='mentorrelationship',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='home.SignedContract'),
        ),
    ]
