# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-17 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0184_auto_20200817_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comrade',
            name='fourth_language',
        ),
        migrations.RemoveField(
            model_name='comrade',
            name='primary_language',
        ),
        migrations.RemoveField(
            model_name='comrade',
            name='second_language',
        ),
        migrations.RemoveField(
            model_name='comrade',
            name='third_language',
        ),
    ]
