# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-19 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0184_auto_20200816_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barrierstoparticipation',
            name='barriers_to_contribution',
        ),
        migrations.AddField(
            model_name='barrierstoparticipation',
            name='country_living_in_during_internship',
            field=models.CharField(default='Unknown', max_length=800, verbose_name='What country will you be living in during the internship?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barrierstoparticipation',
            name='underrepresentation',
            field=models.TextField(default='Unknown', verbose_name='Are you part of an underrepresented group (in the technology industry of the country listed above)? How are you underrepresented?'),
            preserve_default=False,
        ),
    ]
