# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-17 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0185_auto_20200817_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalmentorfeedback',
            name='termination_reason',
        ),
        migrations.RemoveField(
            model_name='initialmentorfeedback',
            name='termination_reason',
        ),
        migrations.RemoveField(
            model_name='midpointmentorfeedback',
            name='termination_reason',
        ),
    ]
