# Generated by Django 3.1 on 2020-08-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0186_auto_20200817_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorinformation',
            name='continuing_contract_work',
            field=models.BooleanField(null=True, verbose_name='Will you be doing contract work during the Outreachy internship period?'),
        ),
        migrations.AlterField(
            model_name='finalmentorfeedback',
            name='organizer_payment_approved',
            field=models.BooleanField(default=None, help_text='Outreachy organizers approve or do not approve to pay this intern.', null=True),
        ),
        migrations.AlterField(
            model_name='initialmentorfeedback',
            name='organizer_payment_approved',
            field=models.BooleanField(default=None, help_text='Outreachy organizers approve or do not approve to pay this intern.', null=True),
        ),
        migrations.AlterField(
            model_name='internselection',
            name='organizer_approved',
            field=models.BooleanField(default=None, help_text='Is this intern and funding information confirmed to be correct by the Outreachy organizers?', null=True),
        ),
        migrations.AlterField(
            model_name='midpointmentorfeedback',
            name='organizer_payment_approved',
            field=models.BooleanField(default=None, help_text='Outreachy organizers approve or do not approve to pay this intern.', null=True),
        ),
    ]
