# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-26 10:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0186_barrierstoparticipation_country_living_in_during_internship_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticAmericanDemographics',
            fields=[
                ('internship_round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.RoundPage')),
                ('total_approved_american_applicants', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_approved_american_bipoc', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='StatisticApplicantCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_living_in_during_internship', models.CharField(max_length=800, verbose_name='Country interns are living in during the internship')),
                ('country_living_in_during_internship_code', models.CharField(max_length=2, verbose_name='ISO 3166-1 alpha-2 country code')),
                ('total_applicants', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='StatisticGenderDemographics',
            fields=[
                ('internship_round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.RoundPage')),
                ('total_transgender_people', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_genderqueer_people', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_men', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_trans_masculine_people', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_women', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_trans_feminine_people', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_non_binary_people', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_who_self_identified_gender', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='StatisticTotalApplied',
            fields=[
                ('internship_round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.RoundPage')),
                ('total_applicants', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_approved', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_pending', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_rejected', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_withdrawn', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AddField(
            model_name='applicantapproval',
            name='collected_statistics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statisticapplicantcountry',
            name='internship_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.RoundPage'),
        ),
    ]
