# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-28 03:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0187_auto_20200826_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundpage',
            name='minimum_days_free_for_non_students',
            field=models.IntegerField(default=49, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='roundpage',
            name='minimum_days_free_for_students',
            field=models.IntegerField(default=49, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
