# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-01 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0188_auto_20200828_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Which category list should this description be under?', max_length=100)),
                ('description', models.CharField(max_length=100, verbose_name='Essay quality description')),
                ('help_text', models.CharField(blank=True, help_text='Help text to further clarify the short essay quality description', max_length=100)),
            ],
            options={
                'ordering': ('category', 'description'),
            },
        ),
        migrations.AlterField(
            model_name='initialapplicationreview',
            name='essay_rating',
            field=models.CharField(choices=[('+3', '+3 - Essay is *strongly* compelling'), ('+2', '+2 - Essay is compelling'), ('+1', '+1 - Essay is *weakly* compelling'), ('??', '?? - Essay questions were too short or unclear to make a decision'), ('0', 'Not rated'), ('-1', '-1 - Essay is not compelling'), ('-2', '-2 - Answers are unrelated to essay questions'), ('-3', '-3 - Essay answers were spam or trolling')], default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='applicantapproval',
            name='essay_qualities',
            field=models.ManyToManyField(blank=True, to='home.EssayQuality'),
        ),
    ]
