# Generated by Django 3.1.2 on 2020-10-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0189_auto_20200901_2240'),
        ('home', '0187_auto_20200817_2207'),
    ]

    operations = [
    ]
