# Generated by Django 3.1.2 on 2020-12-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0191_auto_20201207_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalmentorfeedback',
            name='actions_requested',
            field=models.CharField(choices=[('PAYCONT', 'Pay final intern stipend'), ('1WEEK', 'Delay payment - extend the internship 1 week total'), ('2WEEK', 'Delay payment - extend the internship 2 weeks total'), ('3WEEK', 'Delay payment - extend the internship 3 weeks total'), ('4WEEK', 'Delay payment - extend the internship 4 weeks total'), ('5WEEK', 'Delay payment - extend the internship 5 weeks total'), ('TERMNOPAY', 'Terminate the internship contract, and do not pay the final intern stipend'), ('DONTKNOW', "I don't know what action to recommend, please advise")], default='PAYCONT', max_length=9, verbose_name='What actions are you requesting Outreachy organizers to take, based on your feedback?'),
        ),
        migrations.AlterField(
            model_name='initialmentorfeedback',
            name='actions_requested',
            field=models.CharField(choices=[('PAYCONT', 'Pay the initial intern stipend'), ('1WEEK', 'Delay payment - extend the internship 1 week total'), ('2WEEK', 'Delay payment - extend the internship 2 weeks total'), ('3WEEK', 'Delay payment - extend the internship 3 weeks total'), ('4WEEK', 'Delay payment - extend the internship 4 weeks total'), ('5WEEK', 'Delay payment - extend the internship 5 weeks total'), ('TERMPAY', 'Terminate the internship contract, and pay the initial intern stipend'), ('TERMNOPAY', 'Terminate the internship contract, and do NOT pay the initial intern stipend'), ('DONTKNOW', "I don't know what action to recommend, please advise")], default='PAYCONT', max_length=9, verbose_name='What actions are you requesting Outreachy organizers to take, based on your feedback?'),
        ),
        migrations.AlterField(
            model_name='midpointmentorfeedback',
            name='actions_requested',
            field=models.CharField(choices=[('PAYCONT', 'Pay the midpoint intern stipend'), ('1WEEK', 'Delay payment - extend the internship 1 week total'), ('2WEEK', 'Delay payment - extend the internship 2 weeks total'), ('3WEEK', 'Delay payment - extend the internship 3 weeks total'), ('4WEEK', 'Delay payment - extend the internship 4 weeks total'), ('5WEEK', 'Delay payment - extend the internship 5 weeks total'), ('TERMPAY', 'Terminate the internship contract, and pay the midpoint intern stipend'), ('TERMNOPAY', 'Terminate the internship contract, and do NOT pay the midpoint intern stipend'), ('DONTKNOW', "I don't know what action to recommend, please advise")], default='PAYCONT', max_length=9, verbose_name='What actions are you requesting Outreachy organizers to take, based on your feedback?'),
        ),
    ]
