# Generated by Django 3.1.4 on 2021-01-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0194_auto_20210115_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='general_funding_application',
            field=models.CharField(blank=True, max_length=3000, verbose_name='What humanitarian issues is your community addressing?'),
        ),
    ]
