# Generated by Django 3.1.4 on 2021-01-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0196_auto_20210121_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundpage',
            name='outreachy_chat_timezone_url',
            field=models.URLField(blank=True, verbose_name='URL to display timezone conversions for the Outreachy Twitter chat time'),
        ),
    ]
