# Generated by Django 3.1.6 on 2021-06-01 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0198_auto_20210212_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalinternfeedback',
            name='hours_worked',
            field=models.CharField(choices=[('5H', '5 hours'), ('10H', '10 hours'), ('15H', '15 hours'), ('20H', '20 hours'), ('25H', '25 hours'), ('30H', '30 hours'), ('35H', '35 hours'), ('40H', '40 hours'), ('45H', '45 hours'), ('50H', '50 hours'), ('55H', '55 hours'), ('60H', '60 hours')], help_text='Include time you spend researching questions, communicating with your mentor and the community, reading about the project and the community, working on skills you need in order to complete your tasks, and working on the tasks themselves. Please be honest about the number of hours you are putting in.', max_length=3, verbose_name='What is the average number of hours per week you spend on your Outreachy internship?'),
        ),
        migrations.AlterField(
            model_name='initialinternfeedback',
            name='hours_worked',
            field=models.CharField(choices=[('5H', '5 hours'), ('10H', '10 hours'), ('15H', '15 hours'), ('20H', '20 hours'), ('25H', '25 hours'), ('30H', '30 hours'), ('35H', '35 hours'), ('40H', '40 hours'), ('45H', '45 hours'), ('50H', '50 hours'), ('55H', '55 hours'), ('60H', '60 hours')], help_text='Include time you spend researching questions, communicating with your mentor and the community, reading about the project and the community, working on skills you need in order to complete your tasks, and working on the tasks themselves. Please be honest about the number of hours you are putting in.', max_length=3, verbose_name='What is the average number of hours per week you spend on your Outreachy internship?'),
        ),
        migrations.AlterField(
            model_name='midpointinternfeedback',
            name='hours_worked',
            field=models.CharField(choices=[('5H', '5 hours'), ('10H', '10 hours'), ('15H', '15 hours'), ('20H', '20 hours'), ('25H', '25 hours'), ('30H', '30 hours'), ('35H', '35 hours'), ('40H', '40 hours'), ('45H', '45 hours'), ('50H', '50 hours'), ('55H', '55 hours'), ('60H', '60 hours')], help_text='Include time you spend researching questions, communicating with your mentor and the community, reading about the project and the community, working on skills you need in order to complete your tasks, and working on the tasks themselves. Please be honest about the number of hours you are putting in.', max_length=3, verbose_name='What is the average number of hours per week you spend on your Outreachy internship?'),
        ),
        migrations.CreateModel(
            name='InitialMentorFeedbackV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_edits', models.BooleanField()),
                ('ip_address', models.GenericIPAddressField()),
                ('last_contact', models.DateField(verbose_name='What was the last date you were in contact with your intern?')),
                ('mentors_report', models.TextField(verbose_name='Please provide a paragraph describing what support you are providing as an Outreachy mentor. This will be shared with Outreachy organizers and your community coordinator.')),
                ('full_time_effort', models.BooleanField(verbose_name='Do you believe your Outreachy intern is putting in a full-time, 40 hours a week effort into the internship?')),
                ('organizer_payment_approved', models.BooleanField(default=None, help_text='Outreachy organizers approve or do not approve to pay this intern.', null=True)),
                ('request_extension', models.BooleanField(help_text='Sometimes interns do not put in a full-time effort. In this case, one of the options is to delay payment of their stipend and extend their internship a specific number of weeks. You will be asked to re-evaluate your intern after the extension is done.', verbose_name='Does your intern need an extension?')),
                ('request_termination', models.BooleanField(help_text='Sometimes after several extensions, interns still do not put in a full-time effort. If you believe that your intern would not put in a full-time effort with a further extension, you may request to terminate the internship. The Outreachy organizers will be in touch to discuss the request.', verbose_name='Do you believe the internship should be terminated?')),
                ('mentor_answers_questions', models.BooleanField(verbose_name="Do you (or a co-mentor) answer the intern's questions within 10 hours?")),
                ('intern_asks_questions', models.BooleanField(verbose_name='Does the intern ask you (or a co-mentor) questions when stuck for more than 1 to 3 hours?')),
                ('mentor_support_when_stuck', models.BooleanField(verbose_name='Do you (or a co-mentor) offer more support if the intern is stuck?')),
                ('meets_privately', models.BooleanField(verbose_name='Do you (or a co-mentor) meet privately with the intern?')),
                ('meets_over_phone_or_video_chat', models.BooleanField(verbose_name='Do you (or a co-mentor) meet with the intern over phone or video chat?')),
                ('intern_missed_meetings', models.BooleanField(verbose_name='Has the intern recently missed more than 2 meetings?')),
                ('talk_about_project_progress', models.BooleanField(verbose_name='Does the intern and you (or a co-mentor) talk about project progress at least 3 days a week?')),
                ('blog_created', models.BooleanField(verbose_name='Has the intern created a blog?')),
                ('progress_report', models.TextField(verbose_name="Please provide a paragraph describing your intern's progress on establishing communication with you, connecting to your FOSS community, and ramping up on their first tasks. This will only be shown to Outreachy organizers, your community coordinators, and the Software Freedom Conservancy accounting staff.")),
                ('payment_approved', models.BooleanField(help_text='Please base your answer on whether your intern has put in a full-time, 40 hours a week effort. They should have established communication with you and other mentors, and have started learning how to tackle their first tasks. If you are going to ask for an internship extension, please say no to this question.', verbose_name='Should your Outreachy intern be paid the initial $1,000 payment?')),
                ('extension_date', models.DateField(blank=True, help_text="If you want to extend the internship, please pick a date when you will be asked to update your intern's initial feedback and authorize payment. Internships can be extended for up to five weeks. We don't recommend extending an internship for more than 1 week at initial feedback. Please leave this field blank if you are not asking for an extension.", null=True)),
                ('actions_requested', models.CharField(choices=[('PAYCONT', 'Pay the initial intern stipend'), ('1WEEK', 'Delay payment - extend the internship 1 week total'), ('2WEEK', 'Delay payment - extend the internship 2 weeks total'), ('3WEEK', 'Delay payment - extend the internship 3 weeks total'), ('4WEEK', 'Delay payment - extend the internship 4 weeks total'), ('5WEEK', 'Delay payment - extend the internship 5 weeks total'), ('TERMPAY', 'Terminate the internship contract, and pay the initial intern stipend'), ('TERMNOPAY', 'Terminate the internship contract, and do NOT pay the initial intern stipend'), ('DONTKNOW', "I don't know what action to recommend, please advise")], default='PAYCONT', max_length=9, verbose_name='What actions are you requesting Outreachy organizers to take, based on your feedback?')),
                ('intern_selection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.internselection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InitialInternFeedbackV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_edits', models.BooleanField()),
                ('ip_address', models.GenericIPAddressField()),
                ('last_contact', models.DateField(verbose_name='What was the last date you were in contact with your mentor?')),
                ('hours_worked', models.CharField(choices=[('5H', '5 hours'), ('10H', '10 hours'), ('15H', '15 hours'), ('20H', '20 hours'), ('25H', '25 hours'), ('30H', '30 hours'), ('35H', '35 hours'), ('40H', '40 hours'), ('45H', '45 hours'), ('50H', '50 hours'), ('55H', '55 hours'), ('60H', '60 hours')], help_text='Include time you spend researching questions, communicating with your mentor and the community, reading about the project and the community, working on skills you need in order to complete your tasks, and working on the tasks themselves. Please be honest about the number of hours you are putting in.', max_length=3, verbose_name='What is the average number of hours per week you spend on your Outreachy internship?')),
                ('time_comments', models.TextField(blank=True, help_text="(Optional) If you have not been working 40 hours a week, please let us know why. We want to support you, so let us know if there's anything we can do to help.", max_length=3000)),
                ('mentor_support', models.TextField(verbose_name='Please provide a paragraph describing how your mentor has (or has not) been helping you. This information will only be seen by Outreachy mentors. We want you to be honest with us if you are having trouble with your mentor, so we can help you get a better internship experience.')),
                ('share_mentor_feedback_with_community_coordinator', models.BooleanField(default=False, help_text='If you say yes, community coordinators will be able to see your comments and the data you provided about your mentor. This helps coordinators ensure mentors are responsive, coach mentors if they are not responsive, and collect metrics they can use to fund more Outreachy internships.', verbose_name='(Optional) Do you want us to share feedback about your mentor with community coordinators?')),
                ('mentor_answers_questions', models.BooleanField(verbose_name='Do your mentor(s) answer your questions within 10 hours?')),
                ('intern_asks_questions', models.BooleanField(verbose_name='Do you ask your mentor(s) questions when stuck for more than 1 to 3 hours?')),
                ('mentor_support_when_stuck', models.BooleanField(verbose_name='Do your mentor(s) offer more support if you are stuck?')),
                ('meets_privately', models.BooleanField(verbose_name='Do your mentor(s) meet privately with you?')),
                ('meets_over_phone_or_video_chat', models.BooleanField(verbose_name='Do your mentor(s) meet with you over phone or video chat?')),
                ('intern_missed_meetings', models.BooleanField(verbose_name='Have you recently missed more than 2 meetings with your mentor(s)?')),
                ('talk_about_project_progress', models.BooleanField(verbose_name='Do you and your mentor(s) talk about project progress at least 3 days a week?')),
                ('blog_created', models.BooleanField(verbose_name='Have you created a blog?')),
                ('progress_report', models.TextField(verbose_name='Please provide a paragraph describing your progress on establishing communication with your mentor, and ramping up on your first tasks. This information will only be seen by Outreachy organizers. If you are having any difficulties or facing any barriers, please let us know, so we can help you.')),
                ('intern_selection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.internselection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
