# Generated by Django 3.1.6 on 2021-06-08 22:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0199_auto_20210601_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='internselection',
            name='final_payment_status',
            field=models.CharField(choices=[('WOF', 'Waiting for new or updated feedback from the mentor'), ('UNR', 'Feedback about intern not reviewed'), ('QUE', 'Payment request queued'), ('REQ', 'Payment request sent'), ('DOP', 'Do not pay stipend')], default='WOF', max_length=3),
        ),
        migrations.AddField(
            model_name='internselection',
            name='initial_payment_status',
            field=models.CharField(choices=[('WOF', 'Waiting for new or updated feedback from the mentor'), ('UNR', 'Feedback about intern not reviewed'), ('QUE', 'Payment request queued'), ('REQ', 'Payment request sent'), ('DOP', 'Do not pay stipend')], default='WOF', max_length=3),
        ),
        migrations.AddField(
            model_name='internselection',
            name='midpoint_payment_status',
            field=models.CharField(choices=[('WOF', 'Waiting for new or updated feedback from the mentor'), ('UNR', 'Feedback about intern not reviewed'), ('QUE', 'Payment request queued'), ('REQ', 'Payment request sent'), ('DOP', 'Do not pay stipend')], default='WOF', max_length=3),
        ),
        migrations.AddField(
            model_name='internselection',
            name='organizer_notes',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Outreachy organizer notes'),
        ),
    ]
