# Generated by Django 3.1.13 on 2021-08-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0200_auto_20210727_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priorfossexperience',
            name='prior_contrib_accessibility',
        ),
        migrations.RemoveField(
            model_name='priorfossexperience',
            name='prior_contrib_coding',
        ),
        migrations.RemoveField(
            model_name='priorfossexperience',
            name='prior_contrib_data',
        ),
        migrations.RemoveField(
            model_name='priorfossexperience',
            name='prior_contrib_devops',
        ),
        migrations.RemoveField(
            model_name='priorfossexperience',
            name='prior_contrib_docs',
        ),
        migrations.RemoveField(
            model_name='priorfossexperience',
            name='prior_contrib_events',
        ),
        migrations.RemoveField(
            model_name='priorfossexperience',
            name='prior_contrib_forums',
        ),
        migrations.RemoveField(
            model_name='priorfossexperience',
            name='prior_contrib_illustration',
        ),
        migrations.RemoveField(
            model_name='priorfossexperience',
            name='prior_contrib_issues',
        ),
        migrations.RemoveField(
            model_name='priorfossexperience',
            name='prior_contrib_marketing',
        ),
        migrations.RemoveField(
            model_name='priorfossexperience',
            name='prior_contrib_mentor',
        ),
        migrations.RemoveField(
            model_name='priorfossexperience',
            name='prior_contrib_reviewer',
        ),
        migrations.RemoveField(
            model_name='priorfossexperience',
            name='prior_contrib_security',
        ),
        migrations.RemoveField(
            model_name='priorfossexperience',
            name='prior_contrib_self_identify',
        ),
        migrations.RemoveField(
            model_name='priorfossexperience',
            name='prior_contrib_short_talk',
        ),
        migrations.RemoveField(
            model_name='priorfossexperience',
            name='prior_contrib_testing',
        ),
        migrations.RemoveField(
            model_name='priorfossexperience',
            name='prior_contrib_translate',
        ),
        migrations.RemoveField(
            model_name='priorfossexperience',
            name='prior_contrib_ux',
        ),
        migrations.RemoveField(
            model_name='timecommitmentsummary',
            name='other_time_commitments',
        ),
        migrations.AddField(
            model_name='barrierstoparticipation',
            name='content_warnings',
            field=models.CharField(blank=True, max_length=100, verbose_name='Content warnings'),
        ),
        migrations.AddField(
            model_name='officialschool',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes to display to initial application reviewers'),
        ),
        migrations.AlterField(
            model_name='barrierstoparticipation',
            name='employment_bias',
            field=models.TextField(max_length=1000, verbose_name='What systemic bias or discrimination would you face if you applied for a job in the technology industry of your country?'),
        ),
        migrations.AlterField(
            model_name='barrierstoparticipation',
            name='lacking_representation',
            field=models.TextField(max_length=1000, verbose_name='Does your learning environment have few people who share your identity or background? Please provide details.'),
        ),
        migrations.AlterField(
            model_name='barrierstoparticipation',
            name='systemic_bias',
            field=models.TextField(max_length=1000, verbose_name='What systemic bias or discrimination have you faced while building your skills?'),
        ),
        migrations.AlterField(
            model_name='barrierstoparticipation',
            name='underrepresentation',
            field=models.TextField(max_length=1000, verbose_name='Are you part of an underrepresented group (in the technology industry of the country listed above)? How are you underrepresented?'),
        ),
        migrations.AlterField(
            model_name='priorfossexperience',
            name='prior_contributor',
            field=models.BooleanField(verbose_name='Have you contributed to open source before?'),
        ),
        migrations.AlterField(
            model_name='timecommitmentsummary',
            name='contractor',
            field=models.BooleanField(verbose_name='Are you (or will you be) a contractor?'),
        ),
        migrations.AlterField(
            model_name='timecommitmentsummary',
            name='employed',
            field=models.BooleanField(verbose_name='Are you (or will you be) an employee?'),
        ),
        migrations.AlterField(
            model_name='timecommitmentsummary',
            name='enrolled_as_noncollege_student',
            field=models.BooleanField(verbose_name='Are you (or will you be) enrolled in a coding school or self-paced online courses?'),
        ),
        migrations.AlterField(
            model_name='timecommitmentsummary',
            name='enrolled_as_student',
            field=models.BooleanField(verbose_name='Are you (or will you be) a university or college student?'),
        ),
        migrations.AlterField(
            model_name='timecommitmentsummary',
            name='volunteer_time_commitments',
            field=models.BooleanField(verbose_name='Are you (or will you be) a volunteer? Only say yes if you will volunteer for more than 10 hours per week.'),
        ),
        migrations.AlterField(
            model_name='workeligibility',
            name='eligible_to_work',
            field=models.BooleanField(verbose_name='Are you eligible to work for 40 hours a week in ALL the countries you will be living in for the entire internship period, and five weeks after the internship period ends?'),
        ),
        migrations.AlterField(
            model_name='workeligibility',
            name='student_visa_restrictions',
            field=models.BooleanField(verbose_name='Do you have a student visa?'),
        ),
        migrations.AlterField(
            model_name='workeligibility',
            name='under_export_control',
            field=models.BooleanField(verbose_name='Are you a person or entity restricted by United States of America export controls or sanctions programs?'),
        ),
    ]
