# Generated by Django 3.1.13 on 2021-08-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0201_auto_20210809_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecommitmentsummary',
            name='volunteer_time_commitments',
            field=models.BooleanField(verbose_name='Are you (or will you be) a volunteer?'),
        ),
    ]
