# Generated by Django 3.1.14 on 2021-12-31 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0202_auto_20210809_0831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InitialInternFeedbackV2',
            new_name='Feedback1FromIntern',
        ),
        migrations.RenameModel(
            old_name='InitialMentorFeedbackV2',
            new_name='Feedback1FromMentor',
        ),
    ]
