# Generated by Django 3.1.14 on 2022-03-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0207_feedback4fromintern_feedback4frommentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantapproval',
            name='initial_application_country_living_in_during_internship',
            field=models.CharField(blank=True, max_length=800, verbose_name='Country applicant will be living in during the internship - from initial application'),
        ),
        migrations.AddField(
            model_name='applicantapproval',
            name='initial_application_country_living_in_during_internship_code',
            field=models.CharField(blank=True, max_length=2, verbose_name='Country code from initial application - ISO 3166-1 alpha-2 country code'),
        ),
    ]
