# Generated by Django 3.1.14 on 2022-03-13 03:26

from django.db import migrations

def save_country_from_initial_application(apps, schema_editor):
    # Get models
    ApplicantApproval = apps.get_model('home.ApplicantApproval')
    BarriersToParticipation = apps.get_model('home.BarriersToParticipation')
    initial_applications = ApplicantApproval.objects.all()

    for app in initial_applications:
        # Transfer the country information
        # in BarriersToParticipation to the parent ApplicantApproval object.
        #
        # The BarriersToParticipation object is deleted
        # during the data purge after all initial applications are reviewed.
        # However, we need to save the country the intern is living in
        # so we can pass it onto Software Freedom Conservancy
        try:
            app.initial_application_country_living_in_during_internship = app.barrierstoparticipation.country_living_in_during_internship
            app.initial_application_country_living_in_during_internship_code = app.barrierstoparticipation.country_living_in_during_internship_code
            app.save()
        except BarriersToParticipation.DoesNotExist:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0208_auto_20220313_0325'),
    ]

    operations = [
        migrations.RunPython(save_country_from_initial_application),
    ]
