# Generated by Django 3.1.14 on 2022-05-05 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0209_auto_20220313_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorrelationship',
            name='contract',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.signedcontract'),
        ),
    ]
