# Generated by Django 3.1.14 on 2022-07-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0210_auto_20220505_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='informalchatcontact',
            name='tools_used',
            field=models.CharField(blank=True, max_length=800, verbose_name='What tools or programming languages do you use in these roles?'),
        ),
        migrations.AddField(
            model_name='informalchatcontact',
            name='topics',
            field=models.CharField(blank=True, max_length=800, verbose_name='What topics are you excited to talk to Outreachy interns about?'),
        ),
    ]
