# Generated by Django 3.1.14 on 2022-07-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0211_auto_20220720_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundpage',
            name='sponsorship_per_intern',
            field=models.IntegerField(default=6500),
        ),
    ]
